In [1]:
import math
import numpy as np
from numpy import *
import pandas as pd
import scipy.signal as signal

In [2]:
data=pd.read_csv("D:/20年海洋/3000m以下/修正气象参数/20170101修正nt1.csv"  , encoding = "utf-8")
print(data)

        nt  nx  ny  nl       xlong       xlat        hgt       height  \
0        1   1   1   1  104.101074   1.387764  18.679893    21.906155   
1        1   1   1   2  104.101074   1.387764  18.679893    27.956425   
2        1   1   1   3  104.101074   1.387764  18.679893    32.395200   
3        1   1   1   4  104.101074   1.387764  18.679893    36.432667   
4        1   1   1   5  104.101074   1.387764  18.679893    40.874550   
...     ..  ..  ..  ..         ...        ...        ...          ...   
376645   1  90  93  41  126.461487  22.871384   0.000000  1872.088000   
376646   1  90  93  42  126.461487  22.871384   0.000000  2127.688000   
376647   1  90  93  43  126.461487  22.871384   0.000000  2384.219500   
376648   1  90  93  44  126.461487  22.871384   0.000000  2641.170700   
376649   1  90  93  45  126.461487  22.871384   0.000000  2898.699500   

                  z          e    pressure        Tem  
0          3.226261  29.665482  1000.52014  297.85740  
1          

In [10]:
writer=pd.ExcelWriter("D:/20年海洋/3000m以下/修正波导参数/20170101_00修正波导数据.xlsx")
for i in range(1,94):
    data_i=data.loc[data['ny']==i]
    a=['波导厚度 m']
    a=pd.DataFrame(a)
    a.to_excel(writer,'ny'+str(i),startrow=1,startcol=0,header=None,index=None)
   
    a=['波导所在底部的海拔 m']
    a=pd.DataFrame(a)
    a.to_excel(writer,'ny'+str(i),startrow=9,startcol=0,header=None,index=None)
    
    a=['波导所在顶部的海拔 m']
    a=pd.DataFrame(a)
    a.to_excel(writer,'ny'+str(i),startrow=17,startcol=0,header=None,index=None)
   
    a=['波导所在顶部的温度 K']
    a=pd.DataFrame(a)
    a.to_excel(writer,'ny'+str(i),startrow=25,startcol=0,header=None,index=None)
    
    a=['波导所在顶部的水汽压e hpa']
    a=pd.DataFrame(a)
    a.to_excel(writer,'ny'+str(i),startrow=33,startcol=0,header=None,index=None)
   
    #a=['波导所在顶部水汽混合比']
    #a=pd.DataFrame(a)
    #a.to_excel(writer,'ny'+str(i),startrow=25,startcol=0,header=None,index=None)
    
    a=['相应饱和水汽压E hpa']
    a=pd.DataFrame(a)
    a.to_excel(writer,'ny'+str(i),startrow=41,startcol=0,header=None,index=None)
   
    a=['相对湿度f']
    a=pd.DataFrame(a)
    a.to_excel(writer,'ny'+str(i),startrow=49,startcol=0,header=None,index=None)
    
    a=['波导所在顶部的气压  hpa（mbar）']
    a=pd.DataFrame(a)
    a.to_excel(writer,'ny'+str(i),startrow=57,startcol=0,header=None,index=None)
    
    for j in range(1,91):
        data_j=data_i.loc[data_i['nx']==j]
        e=array(data_j['e'])
        Tem=array(data_j['Tem'])
        Pressure=array(data_j['pressure'])
        height=array(data_j['z'])
        
        m=77.6*Pressure/Tem+3.73*10**5*e/Tem**2+0.157*height
       
        greater=m[signal.argrelextrema(m, np.greater)]
        print (greater.shape[0])
        greaterpoint=signal.argrelextrema(m, np.greater)
        print(greaterpoint)
        
        less=m[signal.argrelextrema(m, np.less)]
        print(less.shape)
        lesspoint=signal.argrelextrema(m, np.less)
        print(lesspoint)
        
        if greater.shape==less.shape:
            mdifference=greater-less
        elif greater.shape[0]>less.shape[0]:
            greater=greater[1:]
            mdifference=greater-less
        else:
            less=less[1:]
            mdifference=greater-less
            
        Height=height[lesspoint]
        HEIGHT=height[greaterpoint]
        
        if Height.shape==HEIGHT.shape:
            heightdifference=Height-HEIGHT
            toppressure=Pressure[lesspoint]
            toptem=Tem[lesspoint]
            x=53.67957-6743.769/toptem-4.8451*np.log(toptem)
            E=np.exp(x)
            tope=e[lesspoint]
            f=tope/E
        elif Height.shape[0]<HEIGHT.shape[0]:
            HEIGHT=HEIGHT[1:]
            heightdifference=Height-HEIGHT
            toppressure=Pressure[lesspoint]
            toppressure=toppressure[1:]
            toptem=Tem[lesspoint]
            toptem=toptem[1:]
            x=53.67957-6743.769/toptem-4.8451*np.log(toptem)
            E=np.exp(x)
            tope=e[lesspoint]
            tope=tope[1:]
            f=tope/E
        else:
            Height=Height[1:]
            heightdifference=Height-HEIGHT
            toppressure=Pressure[lesspoint]
            toppressure=toppressure[1:]
            toptem=Tem[lesspoint]
            toptem=toptem[1:]
            x=53.67957-6743.769/toptem-4.8451*np.log(toptem)
            E=np.exp(x)
            tope=e[lesspoint]
            tope=tope[1:]
            f=tope/E        
        
        heightdifference=pd.DataFrame(heightdifference)
        heightdifference.to_excel(writer,'ny'+str(i),startrow=1,startcol=j,header=None,index=None)
        HEIGHT=pd.DataFrame(HEIGHT)
        HEIGHT.to_excel(writer,'ny'+str(i),startrow=9,startcol=j,header=None,index=None)
        Height=pd.DataFrame(Height)
        Height.to_excel(writer,'ny'+str(i),startrow=17,startcol=j,header=None,index=None)
        toptem=pd.DataFrame(toptem)
        toptem.to_excel(writer,'ny'+str(i),startrow=25,startcol=j,header=None,index=None)
        tope=pd.DataFrame(tope)
        tope.to_excel(writer,'ny'+str(i),startrow=33,startcol=j,header=None,index=None)
        E=pd.DataFrame(E)
        E.to_excel(writer,'ny'+str(i),startrow=41,startcol=j,header=None,index=None)
        f=pd.DataFrame(f)
        f.to_excel(writer,'ny'+str(i),startrow=49,startcol=j,header=None,index=None)
        toppressure=pd.DataFrame(toppressure)
        toppressure.to_excel(writer,'ny'+str(i),startrow=57,startcol=j,header=None,index=None)
writer.save()

2
(array([4, 6], dtype=int64),)
(2,)
(array([5, 7], dtype=int64),)
3
(array([ 1,  9, 11], dtype=int64),)
(3,)
(array([ 2, 10, 12], dtype=int64),)
4
(array([ 1,  3,  6, 12], dtype=int64),)
(4,)
(array([ 2,  4,  7, 13], dtype=int64),)
2
(array([2, 9], dtype=int64),)
(2,)
(array([ 4, 10], dtype=int64),)
2
(array([3, 9], dtype=int64),)
(2,)
(array([ 4, 10], dtype=int64),)
5
(array([ 3,  6,  9, 12, 26], dtype=int64),)
(5,)
(array([ 4,  7, 10, 13, 27], dtype=int64),)
4
(array([ 2,  5, 11, 26], dtype=int64),)
(4,)
(array([ 3,  6, 13, 27], dtype=int64),)
4
(array([ 3,  5, 10, 26], dtype=int64),)
(5,)
(array([ 1,  4,  6, 12, 27], dtype=int64),)
4
(array([ 2,  4,  9, 16], dtype=int64),)
(4,)
(array([ 3,  5, 11, 17], dtype=int64),)
4
(array([ 2,  4,  9, 16], dtype=int64),)
(4,)
(array([ 3,  5, 10, 17], dtype=int64),)
3
(array([2, 5, 9], dtype=int64),)
(4,)
(array([ 1,  4,  6, 11], dtype=int64),)
4
(array([ 2,  4,  6, 11], dtype=int64),)
(4,)
(array([ 3,  5,  7, 12], dtype=int64),)
4
(array([ 3,  

4
(array([ 1, 16, 18, 26], dtype=int64),)
(4,)
(array([ 3, 17, 19, 27], dtype=int64),)
0
(array([], dtype=int64),)
(1,)
(array([2], dtype=int64),)
2
(array([ 5, 11], dtype=int64),)
(2,)
(array([ 6, 12], dtype=int64),)
5
(array([ 4,  7, 12, 17, 26], dtype=int64),)
(5,)
(array([ 5,  8, 13, 18, 27], dtype=int64),)
3
(array([ 7, 14, 16], dtype=int64),)
(4,)
(array([ 2,  8, 15, 17], dtype=int64),)
4
(array([ 2,  9, 11, 14], dtype=int64),)
(4,)
(array([ 4, 10, 12, 15], dtype=int64),)
4
(array([ 2, 12, 14, 28], dtype=int64),)
(4,)
(array([ 4, 13, 15, 29], dtype=int64),)
5
(array([ 3,  5,  9, 12, 16], dtype=int64),)
(5,)
(array([ 4,  6, 10, 13, 17], dtype=int64),)
3
(array([ 3, 14, 17], dtype=int64),)
(3,)
(array([ 4, 15, 18], dtype=int64),)
3
(array([ 9, 11, 14], dtype=int64),)
(3,)
(array([10, 12, 15], dtype=int64),)
2
(array([ 3, 10], dtype=int64),)
(2,)
(array([ 4, 12], dtype=int64),)
4
(array([ 4,  8, 14, 17], dtype=int64),)
(4,)
(array([ 5,  9, 15, 18], dtype=int64),)
4
(array([ 3,  5,  

(array([1, 7], dtype=int64),)
(2,)
(array([2, 8], dtype=int64),)
0
(array([], dtype=int64),)
(1,)
(array([2], dtype=int64),)
3
(array([ 2,  7, 13], dtype=int64),)
(3,)
(array([ 3,  8, 14], dtype=int64),)
4
(array([ 2,  8, 24, 28], dtype=int64),)
(4,)
(array([ 3, 10, 25, 29], dtype=int64),)
3
(array([4, 6, 9], dtype=int64),)
(4,)
(array([ 1,  5,  7, 10], dtype=int64),)
2
(array([3, 6], dtype=int64),)
(2,)
(array([4, 8], dtype=int64),)
4
(array([ 3,  8, 16, 23], dtype=int64),)
(5,)
(array([ 1,  5, 10, 17, 24], dtype=int64),)
4
(array([ 2,  4,  9, 16], dtype=int64),)
(4,)
(array([ 3,  6, 11, 17], dtype=int64),)
4
(array([ 3,  5, 10, 16], dtype=int64),)
(4,)
(array([ 4,  7, 11, 17], dtype=int64),)
3
(array([3, 6, 9], dtype=int64),)
(3,)
(array([ 5,  7, 11], dtype=int64),)
4
(array([ 1,  3,  8, 16], dtype=int64),)
(4,)
(array([ 2,  5, 10, 17], dtype=int64),)
3
(array([ 2,  6, 27], dtype=int64),)
(3,)
(array([ 3,  7, 28], dtype=int64),)
3
(array([ 1,  3, 27], dtype=int64),)
(3,)
(array([ 2, 

1
(array([12], dtype=int64),)
(1,)
(array([13], dtype=int64),)
1
(array([12], dtype=int64),)
(1,)
(array([13], dtype=int64),)
0
(array([], dtype=int64),)
(1,)
(array([1], dtype=int64),)
4
(array([ 1,  6, 16, 28], dtype=int64),)
(4,)
(array([ 2,  8, 17, 29], dtype=int64),)
4
(array([ 3,  6, 10, 28], dtype=int64),)
(4,)
(array([ 4,  7, 12, 29], dtype=int64),)
3
(array([ 3,  9, 12], dtype=int64),)
(3,)
(array([ 4, 10, 13], dtype=int64),)
5
(array([ 1,  6,  8, 10, 13], dtype=int64),)
(5,)
(array([ 2,  7,  9, 11, 14], dtype=int64),)
5
(array([ 2,  6,  9, 13, 16], dtype=int64),)
(5,)
(array([ 3,  7, 10, 14, 17], dtype=int64),)
4
(array([ 2,  7,  9, 13], dtype=int64),)
(4,)
(array([ 3,  8, 10, 14], dtype=int64),)
4
(array([ 2,  6,  9, 13], dtype=int64),)
(4,)
(array([ 3,  7, 10, 14], dtype=int64),)
4
(array([ 2,  6,  9, 13], dtype=int64),)
(4,)
(array([ 3,  7, 10, 14], dtype=int64),)
4
(array([ 2,  6,  9, 13], dtype=int64),)
(4,)
(array([ 3,  7, 10, 14], dtype=int64),)
5
(array([ 2,  6,  9, 1

2
(array([3, 8], dtype=int64),)
(2,)
(array([ 5, 10], dtype=int64),)
2
(array([1, 6], dtype=int64),)
(2,)
(array([3, 8], dtype=int64),)
1
(array([4], dtype=int64),)
(1,)
(array([5], dtype=int64),)
1
(array([2], dtype=int64),)
(1,)
(array([4], dtype=int64),)
1
(array([22], dtype=int64),)
(2,)
(array([ 2, 23], dtype=int64),)
0
(array([], dtype=int64),)
(1,)
(array([1], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
1
(array([9], dtype=int64),)
(1,)
(array([10], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
1
(array([2], dtype=int64),)
(2,)
(array([1, 3], dtype=int64),)
2
(array([ 9, 11], dtype=int64),)
(3,)
(array([ 1, 10, 12], dtype=int64),)
2
(array([ 9, 11], dtype=int64),)
(3,)
(array([ 1, 10, 12], dtype=int64),)
1
(array([4], dtype=int64),)
(1,)
(array([6], dtype=int64),)
1
(array([6], dtype=int64),)
(1,)
(array([7], dtype=int64),)
3
(array([ 6, 10, 16], dtype=int64),)
(3,)
(array([ 7, 11, 17], dtype=int64),)
1
(array([3], dtype=

1
(array([11], dtype=int64),)
(1,)
(array([12], dtype=int64),)
4
(array([ 2,  7,  9, 12], dtype=int64),)
(4,)
(array([ 5,  8, 10, 13], dtype=int64),)
3
(array([ 4,  6, 19], dtype=int64),)
(3,)
(array([ 5,  8, 20], dtype=int64),)
2
(array([12, 25], dtype=int64),)
(3,)
(array([ 1, 13, 26], dtype=int64),)
2
(array([1, 3], dtype=int64),)
(2,)
(array([2, 4], dtype=int64),)
1
(array([5], dtype=int64),)
(2,)
(array([1, 6], dtype=int64),)
2
(array([11, 15], dtype=int64),)
(2,)
(array([12, 16], dtype=int64),)
1
(array([28], dtype=int64),)
(1,)
(array([29], dtype=int64),)
1
(array([7], dtype=int64),)
(1,)
(array([8], dtype=int64),)
2
(array([ 1, 15], dtype=int64),)
(2,)
(array([ 2, 16], dtype=int64),)
4
(array([ 2,  5,  7, 11], dtype=int64),)
(4,)
(array([ 3,  6,  8, 12], dtype=int64),)
4
(array([ 3,  5,  9, 24], dtype=int64),)
(4,)
(array([ 4,  6, 10, 25], dtype=int64),)
2
(array([ 3, 16], dtype=int64),)
(2,)
(array([ 4, 17], dtype=int64),)
2
(array([2, 7], dtype=int64),)
(2,)
(array([3, 8], dt

(array([ 2,  5, 16, 19], dtype=int64),)
3
(array([1, 3, 6], dtype=int64),)
(3,)
(array([2, 4, 7], dtype=int64),)
2
(array([3, 8], dtype=int64),)
(3,)
(array([ 1,  5, 10], dtype=int64),)
5
(array([ 1,  3,  6, 10, 16], dtype=int64),)
(5,)
(array([ 2,  5,  7, 11, 17], dtype=int64),)
4
(array([ 2,  4, 10, 16], dtype=int64),)
(4,)
(array([ 3,  5, 12, 17], dtype=int64),)
3
(array([ 3,  5, 11], dtype=int64),)
(3,)
(array([ 4,  6, 12], dtype=int64),)
4
(array([ 3,  5,  8, 12], dtype=int64),)
(4,)
(array([ 4,  6,  9, 13], dtype=int64),)
3
(array([ 3,  8, 12], dtype=int64),)
(3,)
(array([ 4,  9, 13], dtype=int64),)
3
(array([ 4,  8, 12], dtype=int64),)
(4,)
(array([ 1,  5,  9, 13], dtype=int64),)
3
(array([ 4,  9, 12], dtype=int64),)
(4,)
(array([ 1,  5, 10, 13], dtype=int64),)
4
(array([ 1,  5,  8, 12], dtype=int64),)
(4,)
(array([ 2,  6, 10, 13], dtype=int64),)
5
(array([ 2,  6,  8, 10, 12], dtype=int64),)
(6,)
(array([ 1,  3,  7,  9, 11, 13], dtype=int64),)
4
(array([ 3,  5,  9, 13], dtype=in

3
(array([ 3,  7, 11], dtype=int64),)
(4,)
(array([ 2,  4,  8, 12], dtype=int64),)
2
(array([ 3, 10], dtype=int64),)
(2,)
(array([ 5, 12], dtype=int64),)
2
(array([4, 7], dtype=int64),)
(3,)
(array([1, 5, 9], dtype=int64),)
1
(array([4], dtype=int64),)
(2,)
(array([2, 6], dtype=int64),)
1
(array([2], dtype=int64),)
(1,)
(array([4], dtype=int64),)
1
(array([1], dtype=int64),)
(1,)
(array([2], dtype=int64),)
1
(array([2], dtype=int64),)
(1,)
(array([4], dtype=int64),)
2
(array([1, 5], dtype=int64),)
(2,)
(array([2, 7], dtype=int64),)
4
(array([ 2,  4,  8, 43], dtype=int64),)
(3,)
(array([ 3,  5, 10], dtype=int64),)
4
(array([ 5,  7, 12, 43], dtype=int64),)
(4,)
(array([ 1,  6,  8, 13], dtype=int64),)
2
(array([ 4, 43], dtype=int64),)
(1,)
(array([5], dtype=int64),)
2
(array([18, 43], dtype=int64),)
(2,)
(array([ 1, 19], dtype=int64),)
2
(array([ 3, 43], dtype=int64),)
(1,)
(array([4], dtype=int64),)
1
(array([12], dtype=int64),)
(1,)
(array([13], dtype=int64),)
4
(array([ 5,  8, 12, 14],

3
(array([ 4, 16, 25], dtype=int64),)
(3,)
(array([ 5, 17, 26], dtype=int64),)
4
(array([ 4, 12, 16, 34], dtype=int64),)
(4,)
(array([ 5, 13, 17, 35], dtype=int64),)
3
(array([ 3,  9, 15], dtype=int64),)
(3,)
(array([ 5, 10, 16], dtype=int64),)
3
(array([ 4,  6, 15], dtype=int64),)
(3,)
(array([ 5,  7, 17], dtype=int64),)
2
(array([ 4, 15], dtype=int64),)
(2,)
(array([ 6, 17], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
1
(array([11], dtype=int64),)
(1,)
(array([12], dtype=int64),)
1
(array([12], dtype=int64),)
(1,)
(array([13], dtype=int64),)
1
(array([12], dtype=int64),)
(1,)
(array([13], dtype=int64),)
1
(array([9], dtype=int64),)
(1,)
(array([10], dtype=int64),)
3
(array([ 1,  7, 15], dtype=int64),)
(3,)
(array([ 2,  9, 16], dtype=int64),)
4
(array([ 2,  4, 16, 18], dtype=int64),)
(5,)
(array([ 1,  3,  6, 17, 19], dtype=int64),)
3
(array([ 2,  7, 18], dtype=int64),)
(4,)
(array([ 1,  4,  8, 19]

6
(array([ 1,  3,  6,  8, 12, 16], dtype=int64),)
(6,)
(array([ 2,  5,  7,  9, 13, 17], dtype=int64),)
4
(array([ 1,  3,  7, 15], dtype=int64),)
(4,)
(array([ 2,  5,  8, 16], dtype=int64),)
3
(array([ 3,  5, 10], dtype=int64),)
(4,)
(array([ 1,  4,  6, 11], dtype=int64),)
4
(array([ 2,  5,  9, 15], dtype=int64),)
(5,)
(array([ 1,  4,  6, 11, 16], dtype=int64),)
2
(array([6, 9], dtype=int64),)
(3,)
(array([ 4,  7, 11], dtype=int64),)
6
(array([ 1,  4,  6, 10, 16, 43], dtype=int64),)
(5,)
(array([ 2,  5,  7, 11, 17], dtype=int64),)
6
(array([ 1,  4,  6, 10, 16, 43], dtype=int64),)
(5,)
(array([ 3,  5,  7, 11, 17], dtype=int64),)
6
(array([ 1,  3,  5, 10, 15, 43], dtype=int64),)
(5,)
(array([ 2,  4,  6, 11, 16], dtype=int64),)
6
(array([ 1,  3,  8, 10, 14, 43], dtype=int64),)
(5,)
(array([ 2,  4,  9, 11, 15], dtype=int64),)
5
(array([ 1,  5,  8, 10, 12], dtype=int64),)
(5,)
(array([ 2,  6,  9, 11, 13], dtype=int64),)
4
(array([ 3,  5,  8, 11], dtype=int64),)
(5,)
(array([ 1,  4,  6,  9, 1

(array([8], dtype=int64),)
2
(array([13, 16], dtype=int64),)
(3,)
(array([ 1, 14, 17], dtype=int64),)
4
(array([ 5,  7, 12, 15], dtype=int64),)
(4,)
(array([ 6,  8, 13, 17], dtype=int64),)
5
(array([ 3,  6,  8, 11, 20], dtype=int64),)
(5,)
(array([ 4,  7,  9, 12, 21], dtype=int64),)
1
(array([7], dtype=int64),)
(1,)
(array([8], dtype=int64),)
3
(array([ 6, 17, 19], dtype=int64),)
(3,)
(array([ 7, 18, 20], dtype=int64),)
2
(array([ 5, 15], dtype=int64),)
(3,)
(array([ 1,  6, 16], dtype=int64),)
1
(array([12], dtype=int64),)
(1,)
(array([13], dtype=int64),)
2
(array([ 2, 11], dtype=int64),)
(2,)
(array([ 3, 12], dtype=int64),)
2
(array([1, 6], dtype=int64),)
(2,)
(array([2, 7], dtype=int64),)
3
(array([ 2,  4, 10], dtype=int64),)
(3,)
(array([ 3,  5, 12], dtype=int64),)
3
(array([3, 5, 7], dtype=int64),)
(4,)
(array([1, 4, 6, 8], dtype=int64),)
3
(array([ 1,  7, 20], dtype=int64),)
(3,)
(array([ 4,  8, 21], dtype=int64),)
4
(array([ 2,  4,  8, 20], dtype=int64),)
(4,)
(array([ 3,  5, 10,

4
(array([ 5,  7, 10, 18], dtype=int64),)
(5,)
(array([ 2,  6,  8, 11, 19], dtype=int64),)
4
(array([ 1,  3,  5, 10], dtype=int64),)
(4,)
(array([ 2,  4,  6, 11], dtype=int64),)
4
(array([ 3,  5,  7, 10], dtype=int64),)
(4,)
(array([ 4,  6,  8, 12], dtype=int64),)
5
(array([ 1,  3,  5,  7, 11], dtype=int64),)
(5,)
(array([ 2,  4,  6,  8, 12], dtype=int64),)
4
(array([ 3,  5,  7, 12], dtype=int64),)
(4,)
(array([ 4,  6,  8, 13], dtype=int64),)
3
(array([ 3,  8, 12], dtype=int64),)
(3,)
(array([ 4,  9, 13], dtype=int64),)
3
(array([ 4,  9, 12], dtype=int64),)
(3,)
(array([ 5, 10, 13], dtype=int64),)
4
(array([ 5,  8, 10, 13], dtype=int64),)
(4,)
(array([ 6,  9, 11, 14], dtype=int64),)
2
(array([6, 9], dtype=int64),)
(3,)
(array([ 1,  7, 10], dtype=int64),)
4
(array([ 2,  7, 10, 14], dtype=int64),)
(4,)
(array([ 3,  8, 11, 15], dtype=int64),)
3
(array([ 3,  9, 15], dtype=int64),)
(4,)
(array([ 1,  4, 10, 16], dtype=int64),)
3
(array([ 1,  5, 10], dtype=int64),)
(3,)
(array([ 2,  6, 11], d

2
(array([11, 15], dtype=int64),)
(2,)
(array([12, 16], dtype=int64),)
3
(array([ 5, 13, 15], dtype=int64),)
(3,)
(array([ 6, 14, 16], dtype=int64),)
3
(array([ 5, 11, 14], dtype=int64),)
(3,)
(array([ 6, 12, 15], dtype=int64),)
4
(array([ 5, 10, 14, 18], dtype=int64),)
(4,)
(array([ 6, 11, 15, 19], dtype=int64),)
5
(array([ 5, 12, 14, 16, 18], dtype=int64),)
(5,)
(array([ 6, 13, 15, 17, 19], dtype=int64),)
4
(array([ 5,  9, 12, 18], dtype=int64),)
(4,)
(array([ 6, 11, 14, 19], dtype=int64),)
4
(array([ 1,  8, 13, 25], dtype=int64),)
(4,)
(array([ 2, 11, 14, 26], dtype=int64),)
5
(array([ 4,  7, 10, 13, 18], dtype=int64),)
(5,)
(array([ 5,  9, 11, 14, 19], dtype=int64),)
5
(array([ 4,  7,  9, 12, 18], dtype=int64),)
(5,)
(array([ 5,  8, 11, 13, 19], dtype=int64),)
3
(array([ 5,  8, 11], dtype=int64),)
(3,)
(array([ 7, 10, 12], dtype=int64),)
3
(array([ 5,  9, 11], dtype=int64),)
(3,)
(array([ 8, 10, 12], dtype=int64),)
4
(array([ 2,  4,  8, 10], dtype=int64),)
(4,)
(array([ 3,  7,  9, 

5
(array([ 1,  4,  6, 10, 12], dtype=int64),)
(5,)
(array([ 3,  5,  7, 11, 13], dtype=int64),)
5
(array([ 1,  3,  5, 10, 12], dtype=int64),)
(5,)
(array([ 2,  4,  6, 11, 13], dtype=int64),)
4
(array([ 3,  5,  9, 12], dtype=int64),)
(4,)
(array([ 4,  6, 10, 13], dtype=int64),)
5
(array([ 1,  4,  8, 12, 15], dtype=int64),)
(5,)
(array([ 3,  5,  9, 13, 16], dtype=int64),)
2
(array([3, 7], dtype=int64),)
(3,)
(array([2, 4, 8], dtype=int64),)
3
(array([ 2,  9, 13], dtype=int64),)
(3,)
(array([ 3, 10, 14], dtype=int64),)
3
(array([ 1,  8, 12], dtype=int64),)
(3,)
(array([ 2,  9, 13], dtype=int64),)
4
(array([ 5,  7,  9, 12], dtype=int64),)
(4,)
(array([ 6,  8, 10, 13], dtype=int64),)
4
(array([ 1,  4,  8, 12], dtype=int64),)
(4,)
(array([ 2,  5,  9, 13], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
1
(array([8], dtype=int64),)
(2,)
(array([1, 9], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
2
(array([4, 9], dtype=int64),)
(3,)
(array(

4
(array([ 1,  4, 15, 18], dtype=int64),)
(4,)
(array([ 2,  5, 16, 19], dtype=int64),)
3
(array([ 4, 15, 18], dtype=int64),)
(4,)
(array([ 1,  5, 16, 19], dtype=int64),)
3
(array([ 4, 15, 18], dtype=int64),)
(3,)
(array([ 5, 16, 19], dtype=int64),)
3
(array([ 4, 15, 18], dtype=int64),)
(4,)
(array([ 1,  5, 16, 19], dtype=int64),)
1
(array([18], dtype=int64),)
(1,)
(array([19], dtype=int64),)
1
(array([1], dtype=int64),)
(1,)
(array([2], dtype=int64),)
1
(array([2], dtype=int64),)
(1,)
(array([4], dtype=int64),)
1
(array([3], dtype=int64),)
(1,)
(array([4], dtype=int64),)
1
(array([2], dtype=int64),)
(1,)
(array([4], dtype=int64),)
1
(array([1], dtype=int64),)
(1,)
(array([3], dtype=int64),)
0
(array([], dtype=int64),)
(1,)
(array([1], dtype=int64),)
2
(array([ 1, 14], dtype=int64),)
(2,)
(array([ 3, 15], dtype=int64),)
2
(array([ 5, 11], dtype=int64),)
(3,)
(array([ 2,  6, 12], dtype=int64),)
2
(array([5, 9], dtype=int64),)
(2,)
(array([ 6, 11], dtype=int64),)
3
(array([ 3,  5, 10], dt

3
(array([ 5,  9, 14], dtype=int64),)
(3,)
(array([ 6, 10, 15], dtype=int64),)
2
(array([10, 12], dtype=int64),)
(2,)
(array([11, 13], dtype=int64),)
2
(array([1, 8], dtype=int64),)
(2,)
(array([2, 9], dtype=int64),)
3
(array([ 2,  9, 16], dtype=int64),)
(3,)
(array([ 3, 10, 17], dtype=int64),)
2
(array([ 3, 10], dtype=int64),)
(2,)
(array([ 4, 11], dtype=int64),)
2
(array([1, 5], dtype=int64),)
(2,)
(array([2, 6], dtype=int64),)
2
(array([2, 6], dtype=int64),)
(2,)
(array([3, 7], dtype=int64),)
4
(array([ 1,  3,  7, 12], dtype=int64),)
(4,)
(array([ 2,  4,  8, 13], dtype=int64),)
2
(array([4, 8], dtype=int64),)
(3,)
(array([1, 5, 9], dtype=int64),)
2
(array([5, 9], dtype=int64),)
(3,)
(array([ 2,  6, 10], dtype=int64),)
5
(array([ 1,  3,  5, 10, 24], dtype=int64),)
(5,)
(array([ 2,  4,  7, 11, 25], dtype=int64),)
5
(array([ 1,  3,  5,  7, 11], dtype=int64),)
(5,)
(array([ 2,  4,  6,  8, 12], dtype=int64),)
4
(array([ 1,  4,  8, 11], dtype=int64),)
(4,)
(array([ 2,  6,  9, 12], dtype=i

6
(array([ 2,  4,  8, 10, 12, 18], dtype=int64),)
(7,)
(array([ 1,  3,  6,  9, 11, 13, 19], dtype=int64),)
5
(array([ 1,  3,  8, 11, 43], dtype=int64),)
(4,)
(array([ 2,  5,  9, 12], dtype=int64),)
4
(array([ 3,  8, 10, 43], dtype=int64),)
(4,)
(array([ 1,  5,  9, 11], dtype=int64),)
4
(array([ 4,  7, 10, 43], dtype=int64),)
(4,)
(array([ 1,  5,  8, 12], dtype=int64),)
3
(array([ 1,  4, 10], dtype=int64),)
(3,)
(array([ 2,  5, 12], dtype=int64),)
4
(array([ 1,  3,  8, 10], dtype=int64),)
(4,)
(array([ 2,  5,  9, 11], dtype=int64),)
6
(array([ 1,  4,  8, 11, 22, 43], dtype=int64),)
(5,)
(array([ 2,  5,  9, 12, 23], dtype=int64),)
5
(array([ 2,  5,  9, 12, 43], dtype=int64),)
(5,)
(array([ 1,  3,  6, 10, 13], dtype=int64),)
4
(array([ 2,  8, 12, 43], dtype=int64),)
(3,)
(array([ 3,  9, 13], dtype=int64),)
5
(array([ 1,  3,  9, 13, 43], dtype=int64),)
(4,)
(array([ 2,  4, 10, 14], dtype=int64),)
5
(array([ 1,  3,  9, 13, 43], dtype=int64),)
(4,)
(array([ 2,  4, 10, 14], dtype=int64),)
4
(

(array([ 4, 12], dtype=int64),)
(3,)
(array([ 1,  5, 13], dtype=int64),)
3
(array([ 4,  8, 12], dtype=int64),)
(3,)
(array([ 6,  9, 13], dtype=int64),)
3
(array([ 2,  4, 11], dtype=int64),)
(3,)
(array([ 3,  6, 12], dtype=int64),)
4
(array([ 1,  4, 10, 22], dtype=int64),)
(4,)
(array([ 3,  5, 12, 23], dtype=int64),)
3
(array([ 1,  3, 10], dtype=int64),)
(3,)
(array([ 2,  4, 12], dtype=int64),)
4
(array([ 1,  3,  6, 10], dtype=int64),)
(4,)
(array([ 2,  5,  7, 12], dtype=int64),)
2
(array([ 3, 10], dtype=int64),)
(2,)
(array([ 4, 11], dtype=int64),)
3
(array([2, 5, 9], dtype=int64),)
(3,)
(array([ 3,  6, 11], dtype=int64),)
4
(array([ 1,  3,  7, 18], dtype=int64),)
(4,)
(array([ 2,  5,  9, 19], dtype=int64),)
2
(array([2, 6], dtype=int64),)
(3,)
(array([1, 4, 7], dtype=int64),)
3
(array([ 1,  4, 17], dtype=int64),)
(3,)
(array([ 3,  6, 18], dtype=int64),)
3
(array([ 1,  3, 16], dtype=int64),)
(3,)
(array([ 2,  5, 17], dtype=int64),)
4
(array([ 1,  3,  5, 15], dtype=int64),)
(4,)
(array(

1
(array([7], dtype=int64),)
(2,)
(array([3, 8], dtype=int64),)
1
(array([4], dtype=int64),)
(2,)
(array([1, 6], dtype=int64),)
1
(array([4], dtype=int64),)
(2,)
(array([2, 6], dtype=int64),)
1
(array([4], dtype=int64),)
(2,)
(array([1, 6], dtype=int64),)
2
(array([ 5, 20], dtype=int64),)
(3,)
(array([ 1,  7, 21], dtype=int64),)
2
(array([1, 7], dtype=int64),)
(2,)
(array([2, 8], dtype=int64),)
1
(array([7], dtype=int64),)
(2,)
(array([3, 9], dtype=int64),)
2
(array([3, 8], dtype=int64),)
(3,)
(array([ 2,  4, 10], dtype=int64),)
2
(array([3, 8], dtype=int64),)
(3,)
(array([ 2,  4, 10], dtype=int64),)
2
(array([1, 9], dtype=int64),)
(2,)
(array([ 2, 11], dtype=int64),)
3
(array([1, 3, 9], dtype=int64),)
(3,)
(array([ 2,  4, 11], dtype=int64),)
3
(array([ 1,  5, 10], dtype=int64),)
(3,)
(array([ 2,  6, 11], dtype=int64),)
3
(array([ 4,  7, 12], dtype=int64),)
(4,)
(array([ 1,  6,  8, 13], dtype=int64),)
2
(array([ 3, 10], dtype=int64),)
(2,)
(array([ 4, 11], dtype=int64),)
1
(array([16],

(array([ 2,  5, 11], dtype=int64),)
2
(array([ 3, 10], dtype=int64),)
(2,)
(array([ 5, 11], dtype=int64),)
2
(array([ 4, 10], dtype=int64),)
(2,)
(array([ 5, 12], dtype=int64),)
3
(array([ 1,  3, 10], dtype=int64),)
(3,)
(array([ 2,  5, 12], dtype=int64),)
3
(array([ 4,  7, 10], dtype=int64),)
(3,)
(array([ 6,  8, 12], dtype=int64),)
3
(array([ 5,  7, 11], dtype=int64),)
(4,)
(array([ 1,  6,  8, 12], dtype=int64),)
4
(array([ 3,  5,  8, 12], dtype=int64),)
(5,)
(array([ 1,  4,  6,  9, 13], dtype=int64),)
5
(array([ 1,  5,  7, 10, 12], dtype=int64),)
(5,)
(array([ 2,  6,  8, 11, 14], dtype=int64),)
5
(array([ 3,  5,  7,  9, 14], dtype=int64),)
(6,)
(array([ 1,  4,  6,  8, 10, 15], dtype=int64),)
4
(array([ 1,  4,  8, 12], dtype=int64),)
(4,)
(array([ 3,  5,  9, 13], dtype=int64),)
3
(array([ 3,  5, 10], dtype=int64),)
(4,)
(array([ 1,  4,  6, 11], dtype=int64),)
2
(array([3, 9], dtype=int64),)
(2,)
(array([ 5, 10], dtype=int64),)
3
(array([ 3,  7, 14], dtype=int64),)
(3,)
(array([ 4,  8

(1,)
(array([18], dtype=int64),)
1
(array([17], dtype=int64),)
(1,)
(array([18], dtype=int64),)
3
(array([ 7, 10, 12], dtype=int64),)
(4,)
(array([ 1,  8, 11, 13], dtype=int64),)
2
(array([ 6, 15], dtype=int64),)
(2,)
(array([ 8, 16], dtype=int64),)
3
(array([ 1,  5, 18], dtype=int64),)
(3,)
(array([ 2,  6, 19], dtype=int64),)
2
(array([ 1, 15], dtype=int64),)
(2,)
(array([ 3, 16], dtype=int64),)
2
(array([ 2, 16], dtype=int64),)
(2,)
(array([ 4, 17], dtype=int64),)
3
(array([ 1,  3, 16], dtype=int64),)
(3,)
(array([ 2,  4, 17], dtype=int64),)
1
(array([3], dtype=int64),)
(1,)
(array([6], dtype=int64),)
1
(array([4], dtype=int64),)
(2,)
(array([1, 6], dtype=int64),)
2
(array([2, 7], dtype=int64),)
(3,)
(array([1, 3, 8], dtype=int64),)
3
(array([1, 3, 7], dtype=int64),)
(3,)
(array([2, 4, 9], dtype=int64),)
2
(array([1, 8], dtype=int64),)
(2,)
(array([ 2, 10], dtype=int64),)
3
(array([2, 4, 9], dtype=int64),)
(3,)
(array([ 3,  5, 11], dtype=int64),)
4
(array([ 1,  3,  5, 10], dtype=int6

3
(array([1, 5, 9], dtype=int64),)
(3,)
(array([ 2,  6, 10], dtype=int64),)
3
(array([ 2,  7, 11], dtype=int64),)
(3,)
(array([ 4,  8, 12], dtype=int64),)
4
(array([ 3,  5,  9, 11], dtype=int64),)
(4,)
(array([ 4,  6, 10, 12], dtype=int64),)
3
(array([ 4,  9, 11], dtype=int64),)
(3,)
(array([ 6, 10, 12], dtype=int64),)
4
(array([ 3,  5,  8, 11], dtype=int64),)
(4,)
(array([ 4,  6,  9, 12], dtype=int64),)
4
(array([ 1,  7, 10, 23], dtype=int64),)
(4,)
(array([ 4,  8, 11, 24], dtype=int64),)
4
(array([ 1,  5,  8, 12], dtype=int64),)
(4,)
(array([ 2,  6,  9, 13], dtype=int64),)
4
(array([ 1,  3,  6, 12], dtype=int64),)
(4,)
(array([ 2,  4,  7, 13], dtype=int64),)
4
(array([ 1,  4,  9, 12], dtype=int64),)
(4,)
(array([ 2,  5, 10, 13], dtype=int64),)
4
(array([ 3,  5,  7, 12], dtype=int64),)
(5,)
(array([ 1,  4,  6,  8, 13], dtype=int64),)
4
(array([ 2,  5,  9, 13], dtype=int64),)
(4,)
(array([ 3,  6, 10, 14], dtype=int64),)
3
(array([ 2,  9, 13], dtype=int64),)
(3,)
(array([ 3, 10, 14], dt

(array([ 3,  5, 10], dtype=int64),)
(3,)
(array([ 4,  6, 11], dtype=int64),)
4
(array([ 1,  7,  9, 12], dtype=int64),)
(4,)
(array([ 2,  8, 11, 13], dtype=int64),)
4
(array([ 2,  8, 10, 12], dtype=int64),)
(4,)
(array([ 3,  9, 11, 13], dtype=int64),)
4
(array([ 2,  7,  9, 12], dtype=int64),)
(4,)
(array([ 3,  8, 10, 13], dtype=int64),)
3
(array([ 2,  8, 12], dtype=int64),)
(3,)
(array([ 3, 10, 13], dtype=int64),)
4
(array([ 2,  5,  9, 12], dtype=int64),)
(4,)
(array([ 3,  6, 10, 13], dtype=int64),)
4
(array([ 1,  4,  8, 11], dtype=int64),)
(4,)
(array([ 2,  5,  9, 12], dtype=int64),)
4
(array([ 1,  4,  8, 11], dtype=int64),)
(4,)
(array([ 2,  5,  9, 12], dtype=int64),)
3
(array([ 4,  8, 11], dtype=int64),)
(4,)
(array([ 1,  5,  9, 12], dtype=int64),)
3
(array([ 4,  8, 11], dtype=int64),)
(4,)
(array([ 2,  5,  9, 12], dtype=int64),)
3
(array([ 4,  8, 11], dtype=int64),)
(4,)
(array([ 1,  5,  9, 12], dtype=int64),)
4
(array([ 3,  5,  7, 10], dtype=int64),)
(5,)
(array([ 1,  4,  6,  8, 12

(array([ 3,  5,  7, 10, 12, 15], dtype=int64),)
(7,)
(array([ 1,  4,  6,  8, 11, 13, 16], dtype=int64),)
7
(array([ 2,  6,  9, 12, 15, 18, 34], dtype=int64),)
(8,)
(array([ 1,  5,  7, 11, 13, 16, 19, 35], dtype=int64),)
6
(array([ 2,  5,  8, 12, 15, 34], dtype=int64),)
(7,)
(array([ 1,  4,  6, 10, 13, 16, 35], dtype=int64),)
6
(array([ 2,  6, 12, 14, 17, 36], dtype=int64),)
(7,)
(array([ 1,  4,  8, 13, 16, 18, 37], dtype=int64),)
3
(array([12, 14, 36], dtype=int64),)
(4,)
(array([ 6, 13, 17, 37], dtype=int64),)
4
(array([12, 14, 34, 36], dtype=int64),)
(5,)
(array([ 4, 13, 17, 35, 37], dtype=int64),)
4
(array([12, 14, 34, 36], dtype=int64),)
(5,)
(array([ 1, 13, 17, 35, 37], dtype=int64),)
5
(array([ 4,  9, 12, 33, 36], dtype=int64),)
(6,)
(array([ 1,  5, 11, 13, 34, 37], dtype=int64),)
1
(array([9], dtype=int64),)
(1,)
(array([10], dtype=int64),)
1
(array([3], dtype=int64),)
(1,)
(array([4], dtype=int64),)
3
(array([ 3,  5, 12], dtype=int64),)
(3,)
(array([ 4,  6, 13], dtype=int64),)


2
(array([ 5, 12], dtype=int64),)
(2,)
(array([ 6, 13], dtype=int64),)
2
(array([ 5, 12], dtype=int64),)
(2,)
(array([ 6, 13], dtype=int64),)
1
(array([5], dtype=int64),)
(1,)
(array([6], dtype=int64),)
1
(array([5], dtype=int64),)
(1,)
(array([6], dtype=int64),)
3
(array([ 5, 10, 12], dtype=int64),)
(3,)
(array([ 6, 11, 13], dtype=int64),)
3
(array([1, 5, 9], dtype=int64),)
(3,)
(array([ 2,  6, 10], dtype=int64),)
3
(array([ 1,  4, 22], dtype=int64),)
(3,)
(array([ 2,  5, 23], dtype=int64),)
2
(array([ 4, 13], dtype=int64),)
(2,)
(array([ 5, 14], dtype=int64),)
4
(array([ 1,  3,  9, 13], dtype=int64),)
(4,)
(array([ 2,  4, 10, 14], dtype=int64),)
5
(array([ 1,  3,  6,  9, 12], dtype=int64),)
(5,)
(array([ 2,  4,  7, 10, 13], dtype=int64),)
6
(array([ 1,  3,  6,  9, 12, 22], dtype=int64),)
(6,)
(array([ 2,  4,  7, 10, 13, 23], dtype=int64),)
5
(array([ 1,  3,  5,  8, 12], dtype=int64),)
(5,)
(array([ 2,  4,  6,  9, 13], dtype=int64),)
3
(array([ 1,  5, 12], dtype=int64),)
(3,)
(array([

2
(array([3, 5], dtype=int64),)
(2,)
(array([4, 6], dtype=int64),)
2
(array([ 5, 12], dtype=int64),)
(2,)
(array([ 6, 13], dtype=int64),)
3
(array([ 5,  8, 10], dtype=int64),)
(3,)
(array([ 6,  9, 12], dtype=int64),)
4
(array([ 2,  5,  7, 10], dtype=int64),)
(4,)
(array([ 3,  6,  9, 11], dtype=int64),)
4
(array([ 2,  5,  7, 11], dtype=int64),)
(5,)
(array([ 1,  3,  6,  9, 12], dtype=int64),)
4
(array([ 1,  5,  7, 11], dtype=int64),)
(4,)
(array([ 2,  6,  9, 12], dtype=int64),)
4
(array([ 1,  4,  7, 11], dtype=int64),)
(4,)
(array([ 2,  5,  9, 12], dtype=int64),)
5
(array([ 1,  4,  6,  8, 11], dtype=int64),)
(5,)
(array([ 2,  5,  7,  9, 12], dtype=int64),)
5
(array([ 1,  4,  6,  8, 11], dtype=int64),)
(5,)
(array([ 2,  5,  7,  9, 12], dtype=int64),)
5
(array([ 3,  5,  8, 11, 16], dtype=int64),)
(6,)
(array([ 1,  4,  7,  9, 13, 17], dtype=int64),)
7
(array([ 1,  3, 10, 12, 16, 19, 37], dtype=int64),)
(7,)
(array([ 2,  7, 11, 13, 17, 20, 38], dtype=int64),)
6
(array([ 3,  8, 12, 16, 18, 3

3
(array([1, 3, 8], dtype=int64),)
(3,)
(array([ 2,  4, 10], dtype=int64),)
5
(array([ 1,  4,  7,  9, 12], dtype=int64),)
(5,)
(array([ 2,  5,  8, 10, 13], dtype=int64),)
3
(array([ 4,  9, 14], dtype=int64),)
(3,)
(array([ 5, 10, 15], dtype=int64),)
2
(array([ 8, 16], dtype=int64),)
(3,)
(array([ 1,  9, 17], dtype=int64),)
4
(array([ 1,  9, 12, 23], dtype=int64),)
(4,)
(array([ 2, 10, 13, 24], dtype=int64),)
2
(array([4, 7], dtype=int64),)
(2,)
(array([5, 8], dtype=int64),)
3
(array([ 4,  9, 12], dtype=int64),)
(3,)
(array([ 5, 10, 13], dtype=int64),)
3
(array([ 2, 10, 14], dtype=int64),)
(3,)
(array([ 3, 11, 15], dtype=int64),)
3
(array([ 5,  8, 23], dtype=int64),)
(4,)
(array([ 1,  6,  9, 24], dtype=int64),)
4
(array([ 4,  8, 13, 23], dtype=int64),)
(5,)
(array([ 1,  5,  9, 14, 24], dtype=int64),)
5
(array([ 1,  4,  8, 12, 23], dtype=int64),)
(5,)
(array([ 2,  5,  9, 13, 24], dtype=int64),)
4
(array([ 1,  5,  8, 12], dtype=int64),)
(4,)
(array([ 2,  6,  9, 13], dtype=int64),)
4
(arra

3
(array([ 3,  5, 10], dtype=int64),)
(4,)
(array([ 2,  4,  6, 11], dtype=int64),)
3
(array([ 3,  7, 10], dtype=int64),)
(4,)
(array([ 1,  5,  8, 12], dtype=int64),)
3
(array([ 5,  7, 10], dtype=int64),)
(3,)
(array([ 6,  9, 12], dtype=int64),)
4
(array([ 1,  4,  8, 10], dtype=int64),)
(4,)
(array([ 2,  5,  9, 12], dtype=int64),)
4
(array([ 3,  9, 12, 14], dtype=int64),)
(4,)
(array([ 4, 10, 13, 15], dtype=int64),)
1
(array([2], dtype=int64),)
(2,)
(array([1, 3], dtype=int64),)
2
(array([12, 17], dtype=int64),)
(3,)
(array([ 2, 13, 18], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
2
(array([7, 9], dtype=int64),)
(2,)
(array([ 8, 10], dtype=int64),)
3
(array([1, 5, 8], dtype=int64),)
(3,)
(array([2, 6, 9], dtype=int64),)
3
(array([ 4,  9, 12], dtype=int64),)
(3,)
(array([ 5, 10, 13], dtype=int64),)
3
(array([ 7, 10, 12], dtype=int64),)
(3,)
(array([ 9, 11, 13], dtype=int64),)
2
(array([3, 9], dtype=int64),)
(2,)
(array([ 7, 11], dtype=int64),)
4
(array([ 3, 

(array([3, 6, 8], dtype=int64),)
(3,)
(array([4, 7, 9], dtype=int64),)
2
(array([1, 6], dtype=int64),)
(2,)
(array([3, 7], dtype=int64),)
3
(array([1, 3, 8], dtype=int64),)
(3,)
(array([2, 4, 9], dtype=int64),)
3
(array([ 3,  5, 12], dtype=int64),)
(3,)
(array([ 4,  6, 13], dtype=int64),)
3
(array([ 8, 10, 14], dtype=int64),)
(3,)
(array([ 9, 12, 15], dtype=int64),)
3
(array([ 4, 13, 15], dtype=int64),)
(3,)
(array([ 5, 14, 16], dtype=int64),)
2
(array([10, 14], dtype=int64),)
(2,)
(array([11, 16], dtype=int64),)
2
(array([11, 14], dtype=int64),)
(2,)
(array([12, 16], dtype=int64),)
2
(array([12, 15], dtype=int64),)
(2,)
(array([13, 16], dtype=int64),)
2
(array([13, 15], dtype=int64),)
(2,)
(array([14, 17], dtype=int64),)
2
(array([13, 16], dtype=int64),)
(2,)
(array([14, 17], dtype=int64),)
3
(array([10, 14, 17], dtype=int64),)
(3,)
(array([11, 15, 18], dtype=int64),)
2
(array([14, 18], dtype=int64),)
(2,)
(array([15, 19], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dty

4
(array([ 1,  4,  8, 10], dtype=int64),)
(4,)
(array([ 2,  6,  9, 12], dtype=int64),)
2
(array([3, 9], dtype=int64),)
(3,)
(array([ 1,  6, 11], dtype=int64),)
3
(array([ 2,  8, 37], dtype=int64),)
(3,)
(array([ 5,  9, 38], dtype=int64),)
2
(array([2, 7], dtype=int64),)
(3,)
(array([1, 4, 8], dtype=int64),)
3
(array([ 3,  5, 18], dtype=int64),)
(4,)
(array([ 2,  4,  7, 19], dtype=int64),)
2
(array([3, 5], dtype=int64),)
(3,)
(array([2, 4, 7], dtype=int64),)
3
(array([ 3,  7, 19], dtype=int64),)
(4,)
(array([ 1,  4,  8, 20], dtype=int64),)
3
(array([1, 3, 8], dtype=int64),)
(3,)
(array([2, 5, 9], dtype=int64),)
3
(array([2, 5, 8], dtype=int64),)
(3,)
(array([ 4,  6, 10], dtype=int64),)
3
(array([ 4,  7, 10], dtype=int64),)
(3,)
(array([ 6,  8, 11], dtype=int64),)
3
(array([ 5,  9, 12], dtype=int64),)
(3,)
(array([ 6, 11, 13], dtype=int64),)
3
(array([ 4, 12, 14], dtype=int64),)
(3,)
(array([ 5, 13, 15], dtype=int64),)
2
(array([ 1, 10], dtype=int64),)
(2,)
(array([ 2, 11], dtype=int64),

3
(array([ 1,  4, 11], dtype=int64),)
(3,)
(array([ 2,  5, 13], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
1
(array([1], dtype=int64),)
(1,)
(array([4], dtype=int64),)
0
(array([], dtype=int64),)
(1,)
(array([1], dtype=int64),)
1
(array([8], dtype=int64),)
(1,)
(array([9], dtype=int64),)
1
(array([6], dtype=int64),)
(1,)
(array([7], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
1
(array([8], dtype=int64),)
(1,)
(array([9], dtype=int64),)
1
(array([8], dtype=int64),)
(1,)
(array([9], dtype=int64),)
1
(array([15], dtype=int64),)
(1,)
(array([16], dtype=int64),)
1
(array([8], dtype=int64),)
(1,)
(array([9], dtype=int64),)
1
(array([5], dtype=int64),)
(1,)
(array([7], dtype=int64),)
2
(array([ 7, 16], dtype=int64),)
(2,)
(array([ 8, 17], dtype=int64),)
2
(array([ 3, 13], dtype=int64),)
(2,)
(array([ 4, 14], dtype=in

5
(array([ 2,  6,  8, 13, 22], dtype=int64),)
(6,)
(array([ 1,  3,  7,  9, 14, 23], dtype=int64),)
4
(array([ 3,  6, 10, 13], dtype=int64),)
(4,)
(array([ 4,  7, 11, 14], dtype=int64),)
6
(array([ 1,  3,  6,  8, 12, 22], dtype=int64),)
(6,)
(array([ 2,  4,  7,  9, 13, 23], dtype=int64),)
4
(array([ 3,  5,  8, 12], dtype=int64),)
(5,)
(array([ 1,  4,  6,  9, 13], dtype=int64),)
4
(array([ 1,  4,  8, 11], dtype=int64),)
(4,)
(array([ 2,  5,  9, 12], dtype=int64),)
3
(array([ 3,  5, 10], dtype=int64),)
(4,)
(array([ 1,  4,  6, 11], dtype=int64),)
3
(array([2, 5, 8], dtype=int64),)
(3,)
(array([4, 6, 9], dtype=int64),)
3
(array([3, 7, 9], dtype=int64),)
(4,)
(array([ 1,  4,  8, 10], dtype=int64),)
5
(array([ 2,  5,  7,  9, 19], dtype=int64),)
(6,)
(array([ 1,  4,  6,  8, 10, 20], dtype=int64),)
3
(array([3, 5, 8], dtype=int64),)
(4,)
(array([1, 4, 6, 9], dtype=int64),)
3
(array([1, 3, 8], dtype=int64),)
(3,)
(array([ 2,  5, 10], dtype=int64),)
3
(array([2, 5, 9], dtype=int64),)
(3,)
(array

2
(array([ 4, 11], dtype=int64),)
(2,)
(array([ 5, 12], dtype=int64),)
1
(array([10], dtype=int64),)
(2,)
(array([ 1, 11], dtype=int64),)
4
(array([ 1,  3,  7, 10], dtype=int64),)
(4,)
(array([ 2,  4,  8, 11], dtype=int64),)
2
(array([ 7, 12], dtype=int64),)
(2,)
(array([ 8, 13], dtype=int64),)
1
(array([7], dtype=int64),)
(1,)
(array([8], dtype=int64),)
1
(array([3], dtype=int64),)
(1,)
(array([4], dtype=int64),)
1
(array([8], dtype=int64),)
(2,)
(array([1, 9], dtype=int64),)
2
(array([ 5, 10], dtype=int64),)
(2,)
(array([ 6, 11], dtype=int64),)
1
(array([8], dtype=int64),)
(1,)
(array([9], dtype=int64),)
1
(array([11], dtype=int64),)
(1,)
(array([12], dtype=int64),)
2
(array([ 1, 10], dtype=int64),)
(2,)
(array([ 2, 11], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
1
(array([1], dtype=int64),)
(1,)
(array([2], dtype=int64),)
3
(array([ 3, 15, 17], dtype=int64),)
(3,)
(array([ 4, 16, 18], dtype=int64),)
3
(array([ 9, 15, 17], dtype=int64),)
(3,)
(array([10

2
(array([ 1, 12], dtype=int64),)
(2,)
(array([ 2, 13], dtype=int64),)
3
(array([ 1,  4, 12], dtype=int64),)
(3,)
(array([ 2,  5, 13], dtype=int64),)
4
(array([ 2,  4, 11, 43], dtype=int64),)
(3,)
(array([ 3,  5, 12], dtype=int64),)
5
(array([ 1,  4,  7, 11, 43], dtype=int64),)
(4,)
(array([ 2,  5,  8, 12], dtype=int64),)
4
(array([ 3,  7, 11, 43], dtype=int64),)
(3,)
(array([ 5,  8, 12], dtype=int64),)
5
(array([ 1,  4,  9, 22, 43], dtype=int64),)
(4,)
(array([ 2,  5, 12, 23], dtype=int64),)
2
(array([ 3, 10], dtype=int64),)
(2,)
(array([ 5, 12], dtype=int64),)
2
(array([ 3, 10], dtype=int64),)
(2,)
(array([ 5, 11], dtype=int64),)
3
(array([ 3,  5, 10], dtype=int64),)
(3,)
(array([ 4,  6, 12], dtype=int64),)
4
(array([ 3,  5,  8, 11], dtype=int64),)
(5,)
(array([ 1,  4,  6,  9, 12], dtype=int64),)
4
(array([ 2,  5, 12, 22], dtype=int64),)
(4,)
(array([ 3,  6, 13, 23], dtype=int64),)
4
(array([ 3,  6,  9, 13], dtype=int64),)
(4,)
(array([ 4,  7, 10, 14], dtype=int64),)
4
(array([ 1,  3

1
(array([7], dtype=int64),)
(1,)
(array([8], dtype=int64),)
2
(array([ 4, 15], dtype=int64),)
(3,)
(array([ 1,  5, 16], dtype=int64),)
2
(array([1, 9], dtype=int64),)
(2,)
(array([ 2, 10], dtype=int64),)
1
(array([3], dtype=int64),)
(1,)
(array([4], dtype=int64),)
2
(array([ 1, 10], dtype=int64),)
(2,)
(array([ 2, 11], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
1
(array([1], dtype=int64),)
(1,)
(array([2], dtype=int64),)
2
(array([2, 5], dtype=int64),)
(2,)
(array([3, 6], dtype=int64),)
1
(array([2], dtype=int64),)
(1,)
(array([4], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
2
(array([ 6, 15], dtype=int64),)
(2,)
(array([ 7, 16], dtype=int64),)
2
(array([ 2, 11], dtype=int64),)
(2,)
(array([ 3, 12], dtype=int64),)
2
(array([ 1, 11], dtype=int64),)
(2,)
(array([ 2, 12], dtype=int64),)
1
(array([1], dtype=int64),)
(1,)
(array([2], dtype=int64),)
1
(array([9], dtype=int

(array([ 6, 10, 12, 14], dtype=int64),)
(5,)
(array([ 1,  7, 11, 13, 15], dtype=int64),)
5
(array([ 1,  6,  8, 10, 14], dtype=int64),)
(5,)
(array([ 2,  7,  9, 11, 15], dtype=int64),)
4
(array([ 4,  8, 14, 43], dtype=int64),)
(4,)
(array([ 1,  6, 10, 15], dtype=int64),)
4
(array([ 4, 10, 13, 43], dtype=int64),)
(4,)
(array([ 1,  5, 11, 14], dtype=int64),)
4
(array([ 3,  5,  8, 12], dtype=int64),)
(4,)
(array([ 4,  7,  9, 13], dtype=int64),)
4
(array([ 3,  5,  7, 11], dtype=int64),)
(4,)
(array([ 4,  6,  8, 12], dtype=int64),)
3
(array([ 3,  6, 10], dtype=int64),)
(3,)
(array([ 5,  7, 12], dtype=int64),)
3
(array([ 3,  6, 10], dtype=int64),)
(3,)
(array([ 5,  7, 11], dtype=int64),)
3
(array([ 3,  5, 10], dtype=int64),)
(3,)
(array([ 4,  6, 12], dtype=int64),)
3
(array([ 3,  5, 10], dtype=int64),)
(3,)
(array([ 4,  6, 12], dtype=int64),)
3
(array([ 3,  5, 11], dtype=int64),)
(4,)
(array([ 1,  4,  6, 12], dtype=int64),)
3
(array([ 3,  5, 11], dtype=int64),)
(4,)
(array([ 1,  4,  6, 12], d

2
(array([ 6, 10], dtype=int64),)
(2,)
(array([ 8, 11], dtype=int64),)
1
(array([3], dtype=int64),)
(1,)
(array([4], dtype=int64),)
2
(array([3, 9], dtype=int64),)
(3,)
(array([ 1,  4, 10], dtype=int64),)
2
(array([ 1, 10], dtype=int64),)
(2,)
(array([ 2, 11], dtype=int64),)
3
(array([ 2,  8, 15], dtype=int64),)
(3,)
(array([ 3,  9, 16], dtype=int64),)
2
(array([ 2, 10], dtype=int64),)
(2,)
(array([ 3, 11], dtype=int64),)
2
(array([3, 8], dtype=int64),)
(3,)
(array([1, 4, 9], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
1
(array([15], dtype=int64),)
(1,)
(array([16], dtype=int64),)
3
(array([ 2,  8, 15], dtype=int64),)
(3,)
(array([ 4,  9, 16], dtype=int64),)
1
(array([9], dtype=int64),)
(1,)
(array([12], dtype=int64),)
3
(array([2, 5, 8], dtype=int64),)
(3,)
(array([3, 6, 9], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=

(array([ 5, 10, 12, 14, 43], dtype=int64),)
(5,)
(array([ 1,  6, 11, 13, 15], dtype=int64),)
5
(array([ 9, 12, 14, 24, 43], dtype=int64),)
(5,)
(array([ 1, 10, 13, 15, 25], dtype=int64),)
4
(array([ 5,  9, 14, 43], dtype=int64),)
(4,)
(array([ 1,  6, 10, 15], dtype=int64),)
2
(array([5, 8], dtype=int64),)
(3,)
(array([1, 6, 9], dtype=int64),)
3
(array([ 4, 10, 13], dtype=int64),)
(3,)
(array([ 5, 11, 14], dtype=int64),)
4
(array([ 3,  9, 12, 22], dtype=int64),)
(4,)
(array([ 4, 10, 13, 23], dtype=int64),)
3
(array([ 3,  5, 12], dtype=int64),)
(3,)
(array([ 4,  7, 13], dtype=int64),)
4
(array([ 2,  4,  6, 10], dtype=int64),)
(4,)
(array([ 3,  5,  7, 12], dtype=int64),)
5
(array([ 1,  3,  6, 10, 19], dtype=int64),)
(5,)
(array([ 2,  4,  7, 11, 20], dtype=int64),)
4
(array([ 2,  5,  9, 19], dtype=int64),)
(4,)
(array([ 4,  6, 11, 20], dtype=int64),)
3
(array([1, 4, 9], dtype=int64),)
(3,)
(array([ 3,  6, 11], dtype=int64),)
4
(array([ 1,  4,  8, 18], dtype=int64),)
(4,)
(array([ 3,  6, 10

1
(array([5], dtype=int64),)
(1,)
(array([6], dtype=int64),)
0
(array([], dtype=int64),)
(1,)
(array([1], dtype=int64),)
1
(array([2], dtype=int64),)
(1,)
(array([3], dtype=int64),)
1
(array([14], dtype=int64),)
(1,)
(array([16], dtype=int64),)
1
(array([12], dtype=int64),)
(1,)
(array([13], dtype=int64),)
2
(array([10, 14], dtype=int64),)
(2,)
(array([11, 15], dtype=int64),)
4
(array([ 6,  8, 10, 14], dtype=int64),)
(4,)
(array([ 7,  9, 11, 15], dtype=int64),)
2
(array([ 3, 13], dtype=int64),)
(2,)
(array([ 6, 14], dtype=int64),)
2
(array([ 8, 12], dtype=int64),)
(2,)
(array([10, 14], dtype=int64),)
4
(array([ 1,  7, 11, 16], dtype=int64),)
(4,)
(array([ 2,  8, 12, 17], dtype=int64),)
2
(array([ 9, 14], dtype=int64),)
(2,)
(array([10, 15], dtype=int64),)
2
(array([ 7, 13], dtype=int64),)
(2,)
(array([ 8, 14], dtype=int64),)
2
(array([ 7, 15], dtype=int64),)
(2,)
(array([ 8, 16], dtype=int64),)
1
(array([6], dtype=int64),)
(1,)
(array([8], dtype=int64),)
2
(array([10, 14], dtype=int64)

4
(array([ 2,  4,  9, 12], dtype=int64),)
(4,)
(array([ 3,  5, 10, 13], dtype=int64),)
4
(array([ 4,  7, 13, 43], dtype=int64),)
(4,)
(array([ 1,  5,  8, 14], dtype=int64),)
5
(array([ 3,  6, 10, 14, 43], dtype=int64),)
(4,)
(array([ 4,  7, 11, 15], dtype=int64),)
6
(array([ 3,  8, 11, 14, 23, 43], dtype=int64),)
(5,)
(array([ 4,  9, 13, 15, 24], dtype=int64),)
5
(array([ 4,  8, 11, 14, 43], dtype=int64),)
(4,)
(array([ 5,  9, 12, 15], dtype=int64),)
4
(array([ 3,  6, 10, 43], dtype=int64),)
(3,)
(array([ 4,  8, 11], dtype=int64),)
5
(array([ 1,  5,  8, 12, 43], dtype=int64),)
(4,)
(array([ 3,  6,  9, 13], dtype=int64),)
5
(array([ 1,  4,  7, 12, 43], dtype=int64),)
(4,)
(array([ 2,  5,  8, 13], dtype=int64),)
4
(array([ 1,  4,  6, 11], dtype=int64),)
(4,)
(array([ 2,  5,  7, 12], dtype=int64),)
3
(array([ 2,  4, 10], dtype=int64),)
(3,)
(array([ 3,  7, 12], dtype=int64),)
3
(array([ 1,  4, 10], dtype=int64),)
(3,)
(array([ 3,  7, 11], dtype=int64),)
4
(array([ 1,  5,  9, 16], dtype=in

0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
1
(array([16], dtype=int64),)
(1,)
(array([17], dtype=int64),)
1
(array([1], dtype=int64),)
(1,)
(array([2], dtype=int64),)
1
(array([3], dtype=int64),)
(1,)
(array([4], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
1
(array([7], dtype=int64),)
(1,)
(array([8], dtype=int64),)
2
(array([2, 4], dtype=int64),)
(2,)
(array([3, 5], dtype=int64),)
2
(array([10, 17], dtype=int64),)
(2,)
(array([11, 18], dtype=int64),)
1
(array([10], dtype=int64),)
(1,)
(array([11], dtype=int64),)
1
(array([17], dtype=int64),)
(1,)
(array([18], dtype=int64),)
3
(array([ 1, 12, 15], dtype=int64),)
(3,)
(array([ 2, 13, 16], dtype=int64),)
3
(array([ 9, 12, 17], dtype=int64),)
(3,)
(array([11, 13, 18], dtype=int64),)
2
(array([10, 13], dtype=int64),)
(2,)
(array([11, 14], dtype=int64),)
3
(array([ 5,  7, 15], dtype=int64),)
(3,)
(array([ 6,  8, 16], dtype=int64),)
4
(array([ 1,  3, 10, 16], dtype=int64),)
(4,)
(array([ 2,  4, 1

1
(array([13], dtype=int64),)
(1,)
(array([14], dtype=int64),)
1
(array([14], dtype=int64),)
(1,)
(array([15], dtype=int64),)
1
(array([16], dtype=int64),)
(1,)
(array([17], dtype=int64),)
1
(array([7], dtype=int64),)
(2,)
(array([1, 8], dtype=int64),)
1
(array([3], dtype=int64),)
(1,)
(array([4], dtype=int64),)
2
(array([ 6, 43], dtype=int64),)
(2,)
(array([1, 8], dtype=int64),)
3
(array([ 2,  8, 43], dtype=int64),)
(2,)
(array([ 3, 11], dtype=int64),)
4
(array([ 3,  5, 10, 43], dtype=int64),)
(4,)
(array([ 1,  4,  6, 13], dtype=int64),)
4
(array([ 1,  4, 10, 43], dtype=int64),)
(3,)
(array([ 2,  6, 13], dtype=int64),)
5
(array([ 3,  5, 11, 14, 43], dtype=int64),)
(4,)
(array([ 4,  6, 13, 15], dtype=int64),)
5
(array([ 4,  7, 12, 14, 43], dtype=int64),)
(5,)
(array([ 1,  5,  8, 13, 15], dtype=int64),)
5
(array([ 3,  6,  9, 12, 43], dtype=int64),)
(4,)
(array([ 4,  7, 10, 15], dtype=int64),)
5
(array([ 4,  8, 11, 14, 43], dtype=int64),)
(4,)
(array([ 5,  9, 13, 15], dtype=int64),)
6
(a

(array([3], dtype=int64),)
(1,)
(array([4], dtype=int64),)
1
(array([6], dtype=int64),)
(1,)
(array([7], dtype=int64),)
1
(array([11], dtype=int64),)
(1,)
(array([12], dtype=int64),)
1
(array([15], dtype=int64),)
(1,)
(array([16], dtype=int64),)
2
(array([1, 7], dtype=int64),)
(2,)
(array([2, 8], dtype=int64),)
1
(array([16], dtype=int64),)
(1,)
(array([17], dtype=int64),)
1
(array([11], dtype=int64),)
(1,)
(array([12], dtype=int64),)
1
(array([2], dtype=int64),)
(1,)
(array([3], dtype=int64),)
1
(array([9], dtype=int64),)
(1,)
(array([10], dtype=int64),)
1
(array([11], dtype=int64),)
(1,)
(array([12], dtype=int64),)
2
(array([ 5, 17], dtype=int64),)
(2,)
(array([ 6, 18], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
2
(array([ 7, 17], dtype=int64),)
(2,)
(array([ 8, 18], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
1
(array([9], dtype=int64),)
(1,)
(array([11], dtype=int64),)
3
(array([ 5, 10, 12], dtype=int64),)
(3,)
(array([ 6

3
(array([ 7, 10, 15], dtype=int64),)
(3,)
(array([ 8, 11, 17], dtype=int64),)
2
(array([ 9, 16], dtype=int64),)
(2,)
(array([10, 17], dtype=int64),)
1
(array([14], dtype=int64),)
(1,)
(array([15], dtype=int64),)
1
(array([12], dtype=int64),)
(1,)
(array([13], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
1
(array([14], dtype=int64),)
(1,)
(array([15], dtype=int64),)
1
(array([1], dtype=int64),)
(1,)
(array([2], dtype=int64),)
2
(array([ 2, 14], dtype=int64),)
(2,)
(array([ 4, 15], dtype=int64),)
4
(array([ 1,  5, 12, 14], dtype=int64),)
(4,)
(array([ 2,  7, 13, 15], dtype=int64),)
4
(array([ 3,  9, 12, 14], dtype=int64),)
(5,)
(array([ 2,  4, 11, 13, 15], dtype=int64),)
5
(array([ 1,  3,  6, 12, 43], dtype=int64),)
(4,)
(array([ 2,  4,  7, 13], dtype=int64),)
5
(array([ 1,  3,  6, 12, 43], dtype=int64),)
(4,)
(array([ 2,  4,  7, 13], dtype=int64),)
5
(array([ 1,  6, 12, 14, 43], dtype=int64),)
(4,)
(array([ 2,  8, 13, 15], dtype=int64),)
4
(array([12, 14, 1

0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
1
(array([8], dtype=int64),)
(1,)
(array([9], dtype=int64),)
1
(array([15], dtype=int64),)
(2,)
(array([ 1, 16], dtype=int64),)
1
(array([8], dtype=int64),)
(1,)
(array([9], dtype=int64),)
1
(array([12], dtype=int64),)
(1,)
(array([13], dtype=int64),)
2
(array([4, 6], dtype=int64),)
(2,)
(array([5, 7], dtype=int64),)
2
(array([ 2, 14], dtype=int64),)
(2,)
(array([ 3, 15], dtype=int64),)
2
(array([ 7, 13], dtype=int64),)
(3,)
(array([ 1,  8, 14], dtype=int64),)
4
(array([ 3,  7, 10, 15], dtype=int64),)
(4,)
(array([ 4,  8, 11, 16], dtype=int64),)
1
(array([4], dtype=int64),)
(2,)
(array([1, 5], dtype=int64),)
2
(array([5, 7], dtype=int64),)
(2,)
(array([6, 8], dtype=int64),)
1
(array([3], dtype=int64),)
(1,)
(array([4], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
2
(array([ 1, 34], dtype=int64),)
(2,)
(array([ 2, 35], dtype=int64),)
2
(array

(array([5, 9], dtype=int64),)
(2,)
(array([ 7, 10], dtype=int64),)
2
(array([ 8, 11], dtype=int64),)
(3,)
(array([ 1, 10, 12], dtype=int64),)
4
(array([ 2, 10, 13, 15], dtype=int64),)
(4,)
(array([ 3, 12, 14, 16], dtype=int64),)
3
(array([ 4, 12, 14], dtype=int64),)
(3,)
(array([ 5, 13, 15], dtype=int64),)
3
(array([ 6,  9, 13], dtype=int64),)
(3,)
(array([ 7, 10, 15], dtype=int64),)
2
(array([ 8, 14], dtype=int64),)
(2,)
(array([ 9, 16], dtype=int64),)
2
(array([10, 14], dtype=int64),)
(2,)
(array([11, 16], dtype=int64),)
1
(array([14], dtype=int64),)
(1,)
(array([17], dtype=int64),)
2
(array([ 4, 14], dtype=int64),)
(2,)
(array([ 5, 17], dtype=int64),)
3
(array([12, 14, 16], dtype=int64),)
(3,)
(array([13, 15, 17], dtype=int64),)
3
(array([ 3, 14, 16], dtype=int64),)
(3,)
(array([ 4, 15, 17], dtype=int64),)
2
(array([14, 17], dtype=int64),)
(2,)
(array([15, 18], dtype=int64),)
1
(array([14], dtype=int64),)
(1,)
(array([15], dtype=int64),)
2
(array([14, 16], dtype=int64),)
(3,)
(array

(array([ 2, 11], dtype=int64),)
1
(array([10], dtype=int64),)
(1,)
(array([11], dtype=int64),)
1
(array([6], dtype=int64),)
(1,)
(array([8], dtype=int64),)
2
(array([3, 8], dtype=int64),)
(2,)
(array([ 4, 10], dtype=int64),)
3
(array([ 2, 11, 13], dtype=int64),)
(3,)
(array([ 3, 12, 14], dtype=int64),)
3
(array([ 1, 13, 26], dtype=int64),)
(3,)
(array([ 2, 14, 27], dtype=int64),)
2
(array([ 5, 10], dtype=int64),)
(2,)
(array([ 6, 11], dtype=int64),)
1
(array([7], dtype=int64),)
(1,)
(array([8], dtype=int64),)
2
(array([10, 14], dtype=int64),)
(2,)
(array([11, 15], dtype=int64),)
2
(array([10, 12], dtype=int64),)
(2,)
(array([11, 13], dtype=int64),)
2
(array([ 1, 13], dtype=int64),)
(2,)
(array([ 3, 14], dtype=int64),)
4
(array([ 3,  8, 11, 15], dtype=int64),)
(4,)
(array([ 4,  9, 12, 16], dtype=int64),)
4
(array([ 3,  8, 11, 15], dtype=int64),)
(4,)
(array([ 4,  9, 12, 16], dtype=int64),)
2
(array([ 5, 12], dtype=int64),)
(2,)
(array([ 6, 13], dtype=int64),)
3
(array([ 1,  6, 13], dtyp

5
(array([ 1,  4, 10, 13, 15], dtype=int64),)
(5,)
(array([ 3,  5, 12, 14, 16], dtype=int64),)
3
(array([ 1,  4, 11], dtype=int64),)
(3,)
(array([ 2,  5, 14], dtype=int64),)
2
(array([ 6, 12], dtype=int64),)
(2,)
(array([ 7, 15], dtype=int64),)
3
(array([ 1,  9, 14], dtype=int64),)
(3,)
(array([ 2, 10, 16], dtype=int64),)
2
(array([12, 14], dtype=int64),)
(2,)
(array([13, 17], dtype=int64),)
2
(array([14, 17], dtype=int64),)
(2,)
(array([15, 18], dtype=int64),)
2
(array([14, 17], dtype=int64),)
(3,)
(array([ 1, 15, 18], dtype=int64),)
1
(array([17], dtype=int64),)
(2,)
(array([ 2, 18], dtype=int64),)
2
(array([14, 17], dtype=int64),)
(2,)
(array([15, 18], dtype=int64),)
4
(array([ 5,  9, 14, 43], dtype=int64),)
(3,)
(array([ 6, 10, 16], dtype=int64),)
4
(array([ 4,  8, 29, 43], dtype=int64),)
(3,)
(array([ 6,  9, 30], dtype=int64),)
3
(array([ 2,  5, 43], dtype=int64),)
(2,)
(array([3, 7], dtype=int64),)
1
(array([9], dtype=int64),)
(1,)
(array([10], dtype=int64),)
4
(array([ 4,  7, 12

(array([6], dtype=int64),)
(1,)
(array([7], dtype=int64),)
2
(array([1, 3], dtype=int64),)
(2,)
(array([2, 4], dtype=int64),)
2
(array([ 3, 10], dtype=int64),)
(2,)
(array([ 4, 11], dtype=int64),)
2
(array([4, 9], dtype=int64),)
(2,)
(array([ 5, 11], dtype=int64),)
1
(array([2], dtype=int64),)
(1,)
(array([3], dtype=int64),)
2
(array([ 9, 15], dtype=int64),)
(2,)
(array([10, 16], dtype=int64),)
1
(array([4], dtype=int64),)
(1,)
(array([5], dtype=int64),)
1
(array([7], dtype=int64),)
(2,)
(array([1, 8], dtype=int64),)
1
(array([10], dtype=int64),)
(1,)
(array([11], dtype=int64),)
4
(array([ 2,  6, 11, 15], dtype=int64),)
(4,)
(array([ 4,  7, 13, 16], dtype=int64),)
3
(array([ 3, 13, 16], dtype=int64),)
(3,)
(array([ 5, 14, 17], dtype=int64),)
3
(array([ 3,  7, 13], dtype=int64),)
(4,)
(array([ 1,  4,  8, 14], dtype=int64),)
1
(array([9], dtype=int64),)
(1,)
(array([11], dtype=int64),)
2
(array([ 5, 12], dtype=int64),)
(2,)
(array([ 6, 13], dtype=int64),)
2
(array([ 3, 11], dtype=int64),

(array([ 3, 11], dtype=int64),)
(2,)
(array([ 4, 12], dtype=int64),)
1
(array([10], dtype=int64),)
(1,)
(array([11], dtype=int64),)
2
(array([1, 8], dtype=int64),)
(2,)
(array([2, 9], dtype=int64),)
1
(array([8], dtype=int64),)
(2,)
(array([1, 9], dtype=int64),)
2
(array([1, 8], dtype=int64),)
(2,)
(array([2, 9], dtype=int64),)
2
(array([1, 8], dtype=int64),)
(2,)
(array([2, 9], dtype=int64),)
2
(array([3, 9], dtype=int64),)
(2,)
(array([ 4, 10], dtype=int64),)
3
(array([ 3, 10, 15], dtype=int64),)
(3,)
(array([ 4, 11, 16], dtype=int64),)
2
(array([ 4, 11], dtype=int64),)
(2,)
(array([ 5, 12], dtype=int64),)
3
(array([ 6, 12, 15], dtype=int64),)
(4,)
(array([ 1,  7, 13, 16], dtype=int64),)
3
(array([ 2,  8, 13], dtype=int64),)
(3,)
(array([ 3,  9, 14], dtype=int64),)
2
(array([3, 9], dtype=int64),)
(3,)
(array([ 1,  4, 10], dtype=int64),)
4
(array([ 1,  3, 10, 15], dtype=int64),)
(4,)
(array([ 2,  4, 11, 16], dtype=int64),)
5
(array([ 1,  3, 10, 14, 29], dtype=int64),)
(5,)
(array([ 2,

3
(array([14, 16, 31], dtype=int64),)
(3,)
(array([15, 17, 32], dtype=int64),)
3
(array([ 2, 11, 14], dtype=int64),)
(3,)
(array([ 3, 12, 15], dtype=int64),)
4
(array([ 3,  8, 11, 14], dtype=int64),)
(4,)
(array([ 4,  9, 12, 15], dtype=int64),)
4
(array([ 2,  6, 14, 30], dtype=int64),)
(4,)
(array([ 3,  7, 15, 31], dtype=int64),)
5
(array([ 4,  6, 11, 14, 30], dtype=int64),)
(6,)
(array([ 1,  5,  7, 12, 15, 31], dtype=int64),)
4
(array([ 3, 11, 15, 30], dtype=int64),)
(4,)
(array([ 4, 12, 16, 31], dtype=int64),)
4
(array([ 1,  3, 11, 14], dtype=int64),)
(4,)
(array([ 2,  4, 12, 15], dtype=int64),)
3
(array([ 5, 11, 13], dtype=int64),)
(4,)
(array([ 1,  6, 12, 14], dtype=int64),)
4
(array([ 4,  6, 12, 30], dtype=int64),)
(4,)
(array([ 5,  7, 14, 31], dtype=int64),)
5
(array([ 3,  9, 12, 16, 30], dtype=int64),)
(5,)
(array([ 4, 10, 13, 17, 31], dtype=int64),)
3
(array([ 3, 11, 15], dtype=int64),)
(3,)
(array([ 4, 13, 16], dtype=int64),)
4
(array([ 3,  7, 11, 15], dtype=int64),)
(4,)
(arr

0
(array([], dtype=int64),)
(1,)
(array([1], dtype=int64),)
2
(array([ 4, 30], dtype=int64),)
(2,)
(array([ 5, 31], dtype=int64),)
1
(array([5], dtype=int64),)
(1,)
(array([6], dtype=int64),)
2
(array([1, 5], dtype=int64),)
(2,)
(array([2, 6], dtype=int64),)
2
(array([1, 5], dtype=int64),)
(2,)
(array([2, 6], dtype=int64),)
1
(array([6], dtype=int64),)
(1,)
(array([7], dtype=int64),)
1
(array([6], dtype=int64),)
(1,)
(array([7], dtype=int64),)
1
(array([6], dtype=int64),)
(1,)
(array([7], dtype=int64),)
1
(array([6], dtype=int64),)
(1,)
(array([7], dtype=int64),)
1
(array([6], dtype=int64),)
(2,)
(array([1, 7], dtype=int64),)
1
(array([7], dtype=int64),)
(2,)
(array([1, 8], dtype=int64),)
2
(array([1, 7], dtype=int64),)
(2,)
(array([2, 8], dtype=int64),)
2
(array([2, 8], dtype=int64),)
(2,)
(array([3, 9], dtype=int64),)
2
(array([3, 9], dtype=int64),)
(2,)
(array([ 4, 10], dtype=int64),)
4
(array([ 3, 10, 12, 20], dtype=int64),)
(4,)
(array([ 4, 11, 13, 21], dtype=int64),)
2
(array([ 3

4
(array([ 3,  5, 11, 14], dtype=int64),)
(4,)
(array([ 4,  7, 13, 15], dtype=int64),)
3
(array([ 3,  6, 14], dtype=int64),)
(3,)
(array([ 5,  7, 15], dtype=int64),)
3
(array([ 2,  6, 15], dtype=int64),)
(3,)
(array([ 4,  7, 16], dtype=int64),)
3
(array([ 6, 11, 14], dtype=int64),)
(4,)
(array([ 1,  7, 13, 15], dtype=int64),)
2
(array([ 4, 11], dtype=int64),)
(2,)
(array([ 5, 14], dtype=int64),)
2
(array([ 9, 12], dtype=int64),)
(2,)
(array([10, 13], dtype=int64),)
4
(array([ 6, 10, 15, 30], dtype=int64),)
(4,)
(array([ 7, 13, 16, 31], dtype=int64),)
4
(array([ 5,  9, 14, 30], dtype=int64),)
(4,)
(array([ 6, 11, 15, 31], dtype=int64),)
4
(array([ 4,  7, 11, 14], dtype=int64),)
(4,)
(array([ 5, 10, 12, 15], dtype=int64),)
4
(array([ 7,  9, 11, 13], dtype=int64),)
(4,)
(array([ 8, 10, 12, 14], dtype=int64),)
5
(array([ 4,  7, 11, 13, 15], dtype=int64),)
(5,)
(array([ 5,  9, 12, 14, 16], dtype=int64),)
5
(array([ 1,  3,  8, 11, 20], dtype=int64),)
(5,)
(array([ 2,  4,  9, 13, 21], dtype=i

(array([3], dtype=int64),)
1
(array([11], dtype=int64),)
(1,)
(array([13], dtype=int64),)
2
(array([3, 6], dtype=int64),)
(2,)
(array([4, 7], dtype=int64),)
1
(array([10], dtype=int64),)
(1,)
(array([11], dtype=int64),)
2
(array([ 4, 13], dtype=int64),)
(2,)
(array([ 5, 14], dtype=int64),)
2
(array([ 7, 15], dtype=int64),)
(2,)
(array([ 8, 16], dtype=int64),)
1
(array([15], dtype=int64),)
(1,)
(array([16], dtype=int64),)
1
(array([15], dtype=int64),)
(1,)
(array([16], dtype=int64),)
1
(array([15], dtype=int64),)
(1,)
(array([16], dtype=int64),)
2
(array([ 1, 15], dtype=int64),)
(2,)
(array([ 2, 16], dtype=int64),)
2
(array([ 1, 15], dtype=int64),)
(2,)
(array([ 2, 16], dtype=int64),)
2
(array([ 6, 15], dtype=int64),)
(2,)
(array([ 7, 16], dtype=int64),)
3
(array([ 1,  8, 15], dtype=int64),)
(3,)
(array([ 2,  9, 17], dtype=int64),)
3
(array([ 4,  9, 16], dtype=int64),)
(4,)
(array([ 1,  5, 10, 17], dtype=int64),)
2
(array([ 2, 16], dtype=int64),)
(2,)
(array([ 3, 17], dtype=int64),)
2
(

6
(array([ 1,  6,  8, 11, 15, 30], dtype=int64),)
(6,)
(array([ 2,  7,  9, 13, 16, 31], dtype=int64),)
3
(array([ 3, 11, 14], dtype=int64),)
(3,)
(array([ 4, 13, 15], dtype=int64),)
3
(array([ 3,  6, 11], dtype=int64),)
(3,)
(array([ 4,  7, 12], dtype=int64),)
5
(array([ 1,  3,  6,  9, 11], dtype=int64),)
(5,)
(array([ 2,  4,  7, 10, 12], dtype=int64),)
2
(array([ 5, 31], dtype=int64),)
(2,)
(array([ 6, 32], dtype=int64),)
4
(array([ 3, 11, 14, 31], dtype=int64),)
(4,)
(array([ 4, 12, 15, 32], dtype=int64),)
2
(array([ 7, 12], dtype=int64),)
(2,)
(array([ 8, 13], dtype=int64),)
3
(array([ 4,  9, 16], dtype=int64),)
(3,)
(array([ 5, 12, 17], dtype=int64),)
3
(array([ 6,  8, 14], dtype=int64),)
(3,)
(array([ 7,  9, 15], dtype=int64),)
2
(array([ 4, 13], dtype=int64),)
(2,)
(array([ 7, 14], dtype=int64),)
4
(array([ 1,  3,  5, 12], dtype=int64),)
(4,)
(array([ 2,  4,  6, 14], dtype=int64),)
3
(array([ 3, 12, 15], dtype=int64),)
(4,)
(array([ 1,  5, 13, 16], dtype=int64),)
2
(array([ 3, 11

(array([4], dtype=int64),)
(1,)
(array([5], dtype=int64),)
1
(array([3], dtype=int64),)
(1,)
(array([4], dtype=int64),)
2
(array([ 3, 15], dtype=int64),)
(2,)
(array([ 4, 16], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
1
(array([4], dtype=int64),)
(1,)
(array([6], dtype=int64),)
2
(array([ 1, 10], dtype=int64),)
(2,)
(array([ 2, 11], dtype=int64),)
1
(array([12], dtype=int64),)
(1,)
(array([13], dtype=int64),)
3
(array([ 1,  5, 12], dtype=int64),)
(3,)
(array([ 2,  6, 13], dtype=int64),)
3
(array([ 1,  5, 12], dtype=int64),)
(3,)
(array([ 2,  6, 13], dtype=int64),)
3
(array([ 1,  5, 12], dtype=int64),)
(3,)
(array([ 2,  6, 13], dtype=int64),)
4
(array([ 1,  3,  7, 13], dtype=int64),)
(4,)
(array([ 2,  4,  8, 14], dtype=int64),)
4
(array([ 3,  5,  9, 14], dtype=int64),)
(4,)
(array([ 4,  6, 10, 15], dtype=int64),)
3
(array([ 5,  7, 15], dtype=int64),)
(3,)
(array([ 6,  8, 16], dtype=int64),)
3
(array([ 7, 10, 15], dtype=int64),)
(3,)
(array([ 9, 11, 16], d

3
(array([ 3,  7, 12], dtype=int64),)
(3,)
(array([ 4,  8, 13], dtype=int64),)
3
(array([ 1,  3, 10], dtype=int64),)
(3,)
(array([ 2,  4, 11], dtype=int64),)
3
(array([ 7, 13, 15], dtype=int64),)
(4,)
(array([ 1,  8, 14, 16], dtype=int64),)
3
(array([ 4, 11, 14], dtype=int64),)
(3,)
(array([ 6, 12, 15], dtype=int64),)
5
(array([ 4, 10, 14, 17, 38], dtype=int64),)
(5,)
(array([ 5, 11, 15, 18, 39], dtype=int64),)
4
(array([ 3, 10, 13, 38], dtype=int64),)
(4,)
(array([ 4, 11, 14, 39], dtype=int64),)
4
(array([ 3, 10, 13, 16], dtype=int64),)
(4,)
(array([ 4, 11, 14, 17], dtype=int64),)
4
(array([ 3, 10, 13, 15], dtype=int64),)
(4,)
(array([ 5, 11, 14, 17], dtype=int64),)
3
(array([ 8, 13, 30], dtype=int64),)
(3,)
(array([ 9, 14, 31], dtype=int64),)
3
(array([ 5,  9, 29], dtype=int64),)
(4,)
(array([ 1,  6, 11, 30], dtype=int64),)
2
(array([11, 36], dtype=int64),)
(2,)
(array([12, 37], dtype=int64),)
1
(array([36], dtype=int64),)
(1,)
(array([37], dtype=int64),)
1
(array([13], dtype=int64),

2
(array([ 3, 12], dtype=int64),)
(2,)
(array([ 4, 13], dtype=int64),)
1
(array([8], dtype=int64),)
(1,)
(array([9], dtype=int64),)
2
(array([ 1, 11], dtype=int64),)
(2,)
(array([ 2, 12], dtype=int64),)
3
(array([ 4, 13, 15], dtype=int64),)
(3,)
(array([ 5, 14, 17], dtype=int64),)
3
(array([ 7, 13, 36], dtype=int64),)
(3,)
(array([ 8, 14, 37], dtype=int64),)
3
(array([ 9, 14, 36], dtype=int64),)
(4,)
(array([ 1, 10, 15, 37], dtype=int64),)
3
(array([ 2, 10, 14], dtype=int64),)
(3,)
(array([ 4, 11, 15], dtype=int64),)
3
(array([ 3, 11, 15], dtype=int64),)
(3,)
(array([ 4, 12, 16], dtype=int64),)
4
(array([ 1,  4, 12, 15], dtype=int64),)
(4,)
(array([ 2,  6, 13, 16], dtype=int64),)
2
(array([ 6, 16], dtype=int64),)
(2,)
(array([ 8, 17], dtype=int64),)
2
(array([3, 8], dtype=int64),)
(2,)
(array([ 4, 10], dtype=int64),)
3
(array([ 1,  5, 10], dtype=int64),)
(3,)
(array([ 2,  6, 12], dtype=int64),)
2
(array([ 8, 12], dtype=int64),)
(2,)
(array([ 9, 13], dtype=int64),)
1
(array([5], dtype=i

(array([ 3,  9, 13], dtype=int64),)
(3,)
(array([ 4, 10, 14], dtype=int64),)
4
(array([ 1,  6, 12, 15], dtype=int64),)
(4,)
(array([ 2,  7, 13, 16], dtype=int64),)
5
(array([ 5, 11, 14, 16, 35], dtype=int64),)
(6,)
(array([ 1,  6, 12, 15, 17, 36], dtype=int64),)
5
(array([ 4,  7, 10, 13, 16], dtype=int64),)
(5,)
(array([ 5,  8, 11, 14, 17], dtype=int64),)
4
(array([ 3, 10, 13, 16], dtype=int64),)
(4,)
(array([ 4, 11, 14, 17], dtype=int64),)
4
(array([ 3,  9, 12, 15], dtype=int64),)
(4,)
(array([ 4, 10, 14, 16], dtype=int64),)
4
(array([ 8, 11, 13, 16], dtype=int64),)
(4,)
(array([ 9, 12, 14, 17], dtype=int64),)
2
(array([12, 15], dtype=int64),)
(2,)
(array([13, 17], dtype=int64),)
2
(array([12, 19], dtype=int64),)
(2,)
(array([13, 20], dtype=int64),)
1
(array([3], dtype=int64),)
(1,)
(array([4], dtype=int64),)
3
(array([ 3,  7, 10], dtype=int64),)
(3,)
(array([ 4,  8, 11], dtype=int64),)
1
(array([15], dtype=int64),)
(1,)
(array([16], dtype=int64),)
1
(array([8], dtype=int64),)
(2,)
(a

1
(array([2], dtype=int64),)
(1,)
(array([5], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
3
(array([ 2,  8, 10], dtype=int64),)
(3,)
(array([ 3,  9, 11], dtype=int64),)
1
(array([2], dtype=int64),)
(1,)
(array([3], dtype=int64),)
1
(array([11], dtype=int64),)
(2,)
(array([ 1, 12], dtype=int64),)
1
(array([2], dtype=int64),)
(2,)
(array([1, 3], dtype=int64),)
1
(array([1], dtype=int64),)
(1,)
(array([2], dtype=int64),)
2
(array([10, 33], dtype=int64),)
(2,)
(array([11, 34], dtype=int64),)
2
(array([13, 33], dtype=int64),)
(3,)
(array([ 1, 14, 34], dtype=int64),)
4
(array([ 5,  9, 15, 32], dtype=int64),)
(4,)
(array([ 6, 10, 16, 33], dtype=int64),)
5
(array([ 1,  9, 11, 16, 31], dtype=int64),)
(5,)
(array([ 2, 10, 12, 17, 32], dtype=int64),)
3
(array([ 5, 13, 32], dtype=int64),)
(3,)
(array([ 6, 14, 33], dtype=int64),)
3
(array([ 6, 13, 33], dtype=int64),)
(3,)
(array([ 7, 14, 34], dtype=int64),)
3
(array([ 6, 13, 34], dtype=int64),)
(3,)
(array([ 7, 14, 35]

3
(array([ 2,  9, 13], dtype=int64),)
(3,)
(array([ 3, 10, 14], dtype=int64),)
4
(array([ 1,  8, 12, 35], dtype=int64),)
(4,)
(array([ 2,  9, 14, 36], dtype=int64),)
4
(array([ 2,  8, 12, 35], dtype=int64),)
(4,)
(array([ 3,  9, 14, 36], dtype=int64),)
4
(array([ 2,  5,  8, 12], dtype=int64),)
(4,)
(array([ 3,  6,  9, 14], dtype=int64),)
4
(array([ 3,  9, 12, 37], dtype=int64),)
(4,)
(array([ 4, 10, 14, 38], dtype=int64),)
5
(array([ 2,  5,  8, 12, 37], dtype=int64),)
(5,)
(array([ 3,  6,  9, 14, 38], dtype=int64),)
4
(array([ 1,  6, 11, 15], dtype=int64),)
(4,)
(array([ 2,  7, 13, 16], dtype=int64),)
4
(array([ 4,  9, 14, 16], dtype=int64),)
(4,)
(array([ 5, 11, 15, 17], dtype=int64),)
4
(array([ 3,  7, 13, 15], dtype=int64),)
(4,)
(array([ 4,  9, 14, 16], dtype=int64),)
3
(array([ 3,  6, 12], dtype=int64),)
(3,)
(array([ 4,  8, 13], dtype=int64),)
1
(array([11], dtype=int64),)
(2,)
(array([ 1, 12], dtype=int64),)
3
(array([ 1, 12, 32], dtype=int64),)
(3,)
(array([ 3, 13, 33], dtype=i

(array([2], dtype=int64),)
(1,)
(array([3], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
3
(array([ 1,  8, 13], dtype=int64),)
(3,)
(array([ 2,  9, 14], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
1
(array([3], dtype=int64),)
(1,)
(array([4], dtype=int64),)
2
(array([3, 9], dtype=int64),)
(2,)
(array([ 4, 10], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
2
(array([2, 5], dtype=int64),)
(2,)
(array([3, 6], dtype=int64),)
2
(array([2, 6], dtype=int64),)
(2,)
(array([3, 7], dtype=int64),)
1
(array([5], dtype=int64),)
(1,)
(array([6], dtype=int64),)
2
(array([14, 30], dtype=int64),)
(3,)
(array([ 1, 15, 31], dtype=int64),)
3
(array([ 4,  7, 13], dtype=int64),)
(4,)
(array([ 1,  5,  8, 14], dtype=int64),)
2
(array([29, 32], dtype=int64),)
(3,)
(array([ 1, 30, 33], dtype=int64),)
2
(array([ 3, 29], dtype=int64),)
(2,)
(array([ 5, 30], dtype=int64)

3
(array([ 5, 12, 15], dtype=int64),)
(3,)
(array([ 6, 14, 16], dtype=int64),)
4
(array([ 2,  6, 15, 17], dtype=int64),)
(4,)
(array([ 4,  7, 16, 18], dtype=int64),)
4
(array([ 6, 12, 14, 17], dtype=int64),)
(4,)
(array([ 7, 13, 16, 18], dtype=int64),)
4
(array([ 6, 12, 15, 31], dtype=int64),)
(5,)
(array([ 1,  7, 13, 16, 32], dtype=int64),)
3
(array([ 4, 11, 14], dtype=int64),)
(3,)
(array([ 5, 12, 15], dtype=int64),)
3
(array([ 7, 12, 16], dtype=int64),)
(4,)
(array([ 1,  8, 14, 17], dtype=int64),)
3
(array([ 3,  9, 14], dtype=int64),)
(3,)
(array([ 4, 11, 15], dtype=int64),)
5
(array([ 4,  6, 12, 15, 36], dtype=int64),)
(6,)
(array([ 1,  5,  7, 13, 16, 37], dtype=int64),)
4
(array([ 2, 10, 13, 15], dtype=int64),)
(4,)
(array([ 4, 11, 14, 16], dtype=int64),)
4
(array([ 2,  8, 13, 15], dtype=int64),)
(4,)
(array([ 3,  9, 14, 16], dtype=int64),)
4
(array([ 2,  8, 13, 15], dtype=int64),)
(4,)
(array([ 3,  9, 14, 16], dtype=int64),)
4
(array([ 2,  9, 13, 15], dtype=int64),)
(4,)
(array([

2
(array([11, 13], dtype=int64),)
(2,)
(array([12, 14], dtype=int64),)
2
(array([6, 9], dtype=int64),)
(2,)
(array([ 8, 10], dtype=int64),)
1
(array([1], dtype=int64),)
(1,)
(array([2], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
1
(array([9], dtype=int64),)
(1,)
(array([10], dtype=int64),)
1
(array([2], dtype=int64),)
(1,)
(array([3], dtype=int64),)
2
(array([3, 7], dtype=int64),)
(2,)
(array([4, 8], dtype=int64),)
1
(array([7], dtype=int64),)
(1,)
(array([8], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
3
(array([4, 7, 9], dtype=int64),)
(3,)
(array([ 5,  8, 10], dtype=int64),)
2
(array([ 8, 11], dtype=int64),)
(2,)
(array([ 9, 12], dtype=int64),)
1
(array([13], dtype=int64),)
(1,)
(array([14], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
0
(array([], dtype=int64),)
(0,)
(array([], dtype=int64),)
1
(array([12], dtype=int64),)
(2,)
(array([

0
(array([], dtype=int64),)
(1,)
(array([1], dtype=int64),)
3
(array([ 2, 10, 16], dtype=int64),)
(3,)
(array([ 3, 11, 17], dtype=int64),)
1
(array([29], dtype=int64),)
(2,)
(array([ 1, 30], dtype=int64),)
1
(array([7], dtype=int64),)
(2,)
(array([1, 8], dtype=int64),)
3
(array([ 9, 15, 17], dtype=int64),)
(3,)
(array([10, 16, 19], dtype=int64),)
4
(array([ 4,  7, 11, 14], dtype=int64),)
(5,)
(array([ 1,  5,  8, 13, 15], dtype=int64),)
5
(array([ 6,  9, 13, 15, 33], dtype=int64),)
(6,)
(array([ 1,  7, 10, 14, 16, 34], dtype=int64),)
4
(array([ 2, 10, 13, 16], dtype=int64),)
(4,)
(array([ 3, 11, 14, 17], dtype=int64),)
3
(array([ 5, 11, 14], dtype=int64),)
(3,)
(array([ 6, 12, 15], dtype=int64),)
5
(array([ 1,  8, 13, 15, 31], dtype=int64),)
(5,)
(array([ 2,  9, 14, 16, 32], dtype=int64),)
3
(array([ 4, 10, 14], dtype=int64),)
(3,)
(array([ 5, 11, 16], dtype=int64),)
2
(array([ 7, 12], dtype=int64),)
(3,)
(array([ 1,  8, 13], dtype=int64),)
4
(array([ 4, 10, 13, 16], dtype=int64),)
(4,)