In [1]:
import math
import numpy as np
from numpy import *
import pandas as pd
import scipy.signal as signal

In [2]:
data=pd.read_csv("D:/20年海洋/数据/模拟数据/3000m层数层面导出数据/20170101nt1.csv" , encoding = "utf-8")
print(data)

        nt  nx  ny  nl       xlong       xlat        hgt       height  \
0        1   1   1   1  104.101074   1.387764  18.679893    21.906155   
1        1   1   1   2  104.101074   1.387764  18.679893    27.956425   
2        1   1   1   3  104.101074   1.387764  18.679893    32.395200   
3        1   1   1   4  104.101074   1.387764  18.679893    36.432667   
4        1   1   1   5  104.101074   1.387764  18.679893    40.874550   
...     ..  ..  ..  ..         ...        ...        ...          ...   
376645   1  90  93  41  126.461487  22.871384   0.000000  1872.088000   
376646   1  90  93  42  126.461487  22.871384   0.000000  2127.688000   
376647   1  90  93  43  126.461487  22.871384   0.000000  2384.219500   
376648   1  90  93  44  126.461487  22.871384   0.000000  2641.170700   
376649   1  90  93  45  126.461487  22.871384   0.000000  2898.699500   

                  z          e    pressure        Tem    QVAPOR          MM  \
0          3.226261  29.155886  1007.11865  

In [3]:
writer=pd.ExcelWriter("D:/20年海洋/3000m以下/原始波导参数/20170101_00模拟波导数据.xlsx")
for i in range(1,94):
    data_i=data.loc[data['ny']==i]
    a=['波导厚度 m']
    a=pd.DataFrame(a)
    a.to_excel(writer,'ny'+str(i),startrow=1,startcol=0,header=None,index=None)
   
    a=['波导所在底部的海拔 m']
    a=pd.DataFrame(a)
    a.to_excel(writer,'ny'+str(i),startrow=9,startcol=0,header=None,index=None)
    
    a=['波导所在顶部的海拔 m']
    a=pd.DataFrame(a)
    a.to_excel(writer,'ny'+str(i),startrow=17,startcol=0,header=None,index=None)
   
    a=['波导所在顶部的温度 K']
    a=pd.DataFrame(a)
    a.to_excel(writer,'ny'+str(i),startrow=25,startcol=0,header=None,index=None)
    
    a=['波导所在顶部的水汽压e hpa']
    a=pd.DataFrame(a)
    a.to_excel(writer,'ny'+str(i),startrow=33,startcol=0,header=None,index=None)
   
    #a=['波导所在顶部水汽混合比']
    #a=pd.DataFrame(a)
    #a.to_excel(writer,'ny'+str(i),startrow=25,startcol=0,header=None,index=None)
    
    a=['相应饱和水汽压E hpa']
    a=pd.DataFrame(a)
    a.to_excel(writer,'ny'+str(i),startrow=41,startcol=0,header=None,index=None)
   
    a=['相对湿度f']
    a=pd.DataFrame(a)
    a.to_excel(writer,'ny'+str(i),startrow=49,startcol=0,header=None,index=None)
    
    a=['波导所在顶部的气压  hpa（mbar）']
    a=pd.DataFrame(a)
    a.to_excel(writer,'ny'+str(i),startrow=57,startcol=0,header=None,index=None)
    
    for j in range(1,91):
        data_j=data_i.loc[data_i['nx']==j]
        e=array(data_j['e'])
        Tem=array(data_j['Tem'])
        Pressure=array(data_j['pressure'])
        height=array(data_j['z'])
        
        m=77.6*Pressure/Tem+3.73*10**5*e/Tem**2+0.157*height
       
        greater=m[signal.argrelextrema(m, np.greater)]
        print (greater)
        greaterpoint=signal.argrelextrema(m, np.greater)
        print(greaterpoint)
        
        less=m[signal.argrelextrema(m, np.less)]
        print(less)
        lesspoint=signal.argrelextrema(m, np.less)
        print(lesspoint)
        
        if greater.shape==less.shape:
            mdifference=greater-less
        else:
            less=less[1:]
            mdifference=greater-less
            
        Height=height[lesspoint]
        HEIGHT=height[greaterpoint]
        
        if Height.shape==HEIGHT.shape:
            heightdifference=Height-HEIGHT
            toppressure=Pressure[lesspoint]
            toptem=Tem[lesspoint]
            x=53.67957-6743.769/toptem-4.8451*np.log(toptem)
            E=np.exp(x)
            tope=e[lesspoint]
            f=tope/E
        else:
            Height=Height[1:]
            heightdifference=Height-HEIGHT
            toppressure=Pressure[lesspoint]
            toppressure=toppressure[1:]
            toptem=Tem[lesspoint]
            toptem=toptem[1:]
            x=53.67957-6743.769/toptem-4.8451*np.log(toptem)
            E=np.exp(x)
            tope=e[lesspoint]
            tope=tope[1:]
            f=tope/E        
        
        heightdifference=pd.DataFrame(heightdifference)
        heightdifference.to_excel(writer,'ny'+str(i),startrow=1,startcol=j,header=None,index=None)
        HEIGHT=pd.DataFrame(HEIGHT)
        HEIGHT.to_excel(writer,'ny'+str(i),startrow=9,startcol=j,header=None,index=None)
        Height=pd.DataFrame(Height)
        Height.to_excel(writer,'ny'+str(i),startrow=17,startcol=j,header=None,index=None)
        toptem=pd.DataFrame(toptem)
        toptem.to_excel(writer,'ny'+str(i),startrow=25,startcol=j,header=None,index=None)
        tope=pd.DataFrame(tope)
        tope.to_excel(writer,'ny'+str(i),startrow=33,startcol=j,header=None,index=None)
        E=pd.DataFrame(E)
        E.to_excel(writer,'ny'+str(i),startrow=41,startcol=j,header=None,index=None)
        f=pd.DataFrame(f)
        f.to_excel(writer,'ny'+str(i),startrow=49,startcol=j,header=None,index=None)
        toppressure=pd.DataFrame(toppressure)
        toppressure.to_excel(writer,'ny'+str(i),startrow=57,startcol=j,header=None,index=None)
writer.save()

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[387.94968135]
(array([3], dtype=int64),)
[387.9087457]
(array([4], dtype=int64),)
[388.2466988]
(array([3], dtype=int64),)
[387.91973643]
(array([4], dtype=int64),)
[387.81842881]
(array([3], dtype=int64),)
[387.59091203]
(array([4], dtype=int64),)
[386.97817519]
(array([3], dtype=int64),)
[386.71770947]
(array([4], dtype=int64),)
[386.26715493]
(array([3], dtype=int64),)
[385.8638475]
(array([4], dtype=int64),)
[385.55825383]
(array([3], dtype=int64),)
[385.32519567]
(array([4], dtype=int64),)
[385.39427948]
(array([3], dtype=int64),)
[385.07015349]
(array([4], dtype=int64),)
[385.78404386]
(array([3], dtype=int64),)
[385.61724228]
(array([4], dtype=int64),)
[386.43573509]
(array([3], dtype=int64),)
[386.30344772]
(array([6], dtype=int64),)
[387.24000428 387.14459249]
(array([3, 6], dtype=int64),)
[387.07297925 3

[384.29862052]
(array([3], dtype=int64),)
[384.06839027]
(array([4], dtype=int64),)
[383.04200023]
(array([3], dtype=int64),)
[382.87178456]
(array([4], dtype=int64),)
[381.75512078]
(array([3], dtype=int64),)
[381.7497023]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[380.85681454 380.99483172]
(array([3, 5], dtype=int64),)
[380.8322389  380.99216792]
(array([4, 6], dtype=int64),)
[381.6870536]
(array([3], dtype=int64),)
[381.6556412

[373.76563471]
(array([3], dtype=int64),)
[371.53846192]
(array([4], dtype=int64),)
[372.61176587]
(array([3], dtype=int64),)
[371.81903863]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[365.66283065]
(array([1], dtype=int64),)
[365.65109315]
(array([2], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[357.34010686]
(array([3], dtype=int64),)
[356.70915684]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64)

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], 

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[390.33805343 390.3834387 ]
(array([3, 6], dtype=int64),)
[390.24309649 390.36936808]
(array([5, 7], dtype=int64),)
[389.04760306]
(array([3], dtype=int64),)
[388.76529251]
(array([4], dtype=int64),)
[388.99169547 388.88819889]
(array([3, 6], dty

[366.60253499]
(array([3], dtype=int64),)
[365.15267548]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[372.51489561]
(array([3], dtype=int64),)
[372.01027693]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], 

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], 

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[375.84492635]
(array([3], dtype=int64),)
[375.76238323]
(array([4], dtype=int64),)
[380.27321493]
(array([3], dtype=int64),)
[378.84688372]
(array([4], dtype=int64),)
[408.76203367]
(array([18], dtype=int64),)
[407.92712279]
(array([20], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[400.23110175]
(array([6], dtype=int64),)
[400.22653305]
(array([7], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[392.79918745 393.22544651]
(array([5, 8], dtype=int64),)
[392.76048973 393.20391107]
(array([6, 9], dtype=int64),)
[391.09365461]
(array([3], dtype=int64),)
[390.91174345]
(array([4], dtype=int64),)
[390.40848552]
(array([3], dtype=int64),)
[390.10129078]
(array([4], dtype=int64),)
[389.56950261 389.34369332]
(array([3, 6], dtype=int64),)
[

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[378.81281966]
(array([3], dtype=int64),)
[374.80832372]
(array([4], dtype=int64),)
[413.1438215]
(array([19], dtype=int64),)
[412.09638063]
(array([20], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[396.35254621 396.39300582]
(array([ 8, 11], dtype=int64),)
[396.32803984 396.34049696]
(array([ 9, 12], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[390.25980531 390.74132984]
(array([3, 6], dtype=int64),)
[390.24803596 390.73930599]
(array([4, 7], dtype=int64),)
[389.61208273 389.95348386]
(array([3, 8], dtype=int64),)
[389.37046785 389.89952316]
(array([4, 9], dtype=int64),)
[388.80904993 388.65563082]
(array([3, 8], dtype=int64),)
[388.50057253 388.6301527 ]
(array([4, 9], dtype=int64),)
[387.84788264 388.01694702 387.64775093]
(ar

[387.46437082]
(array([2], dtype=int64),)
[386.90478822]
(array([9], dtype=int64),)
[386.78064659 386.1566143 ]
(array([2, 7], dtype=int64),)
[386.13465088 385.87865303]
(array([ 6, 12], dtype=int64),)
[386.16377148 385.50246508 385.46642264]
(array([ 3,  7, 11], dtype=int64),)
[385.46528953 385.4246362  385.44926234]
(array([ 6, 10, 12], dtype=int64),)
[385.67136027 385.19944847 385.31491566]
(array([ 3,  8, 10], dtype=int64),)
[385.11567948 385.11804727 385.27399478]
(array([ 7,  9, 11], dtype=int64),)
[385.31801728 384.98152817 385.18282239]
(array([3, 6, 9], dtype=int64),)
[384.96408697 384.92210309 385.15823676]
(array([ 5,  7, 10], dtype=int64),)
[384.85135465 384.90710152]
(array([3, 7], dtype=int64),)
[384.65158738 384.80483078]
(array([4, 8], dtype=int64),)
[384.60590508]
(array([3], dtype=int64),)
[384.38258417]
(array([4], dtype=int64),)
[384.38770542 384.55397795]
(array([3, 6], dtype=int64),)
[384.26887726 384.4887864 ]
(array([4, 7], dtype=int64),)
[384.30599229]
(array([

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[387.71304398]
(array([9], dtype=int64),)
[385.38741082]
(array([14], dtype=int64),)
[385.31111114 384.78362404 384.61239817]
(array([2, 6, 9], dtype=int64),)
[385.12911549 384.74650295 384.54127661 384.60671128]
(array([ 1,  5,  8, 10], dtype=int64),)
[386.15974016 385.65960402 385.53095083]
(array([3, 6, 9], dtype=int64),)
[386.0534656  385.63330199 385.47388375 385.39359594]
(array([ 2,  5,  8, 12], dtype=int64),)
[386.9168579  386.89718991 386.63401408]
(array([1, 3, 5]

[387.6167001  387.64679889 387.17593429 387.21876123]
(array([1, 3, 7, 9], dtype=int64),)
[387.52121451 387.12596347 387.14804147 387.12772768]
(array([ 2,  6,  8, 10], dtype=int64),)
[388.14348959 388.01490196]
(array([3, 7], dtype=int64),)
[387.82265099 387.95283418]
(array([6, 8], dtype=int64),)
[388.58182455 388.83459409]
(array([3, 9], dtype=int64),)
[388.42364571 388.74949377]
(array([ 4, 10], dtype=int64),)
[389.08608175 389.09513335]
(array([3, 6], dtype=int64),)
[388.95378051 389.08988016]
(array([4, 7], dtype=int64),)
[389.50778738]
(array([3], dtype=int64),)
[389.45834771]
(array([4], dtype=int64),)
[390.06094429 390.09603658]
(array([3, 6], dtype=int64),)
[389.9426325  390.09573539]
(array([4, 7], dtype=int64),)
[390.57065037 390.60795923]
(array([3, 5], dtype=int64),)
[390.44945379 390.59723829]
(array([4, 6], dtype=int64),)
[391.22226512 391.23581477]
(array([3, 7], dtype=int64),)
[390.99655714 391.23431733]
(array([5, 8], dtype=int64),)
[391.79269895 391.72036347 391.924

[393.11684339 393.18352367]
(array([3, 6], dtype=int64),)
[392.78386695 393.16966643]
(array([4, 7], dtype=int64),)
[393.89251579 394.00334933 394.28724415]
(array([ 3,  6, 10], dtype=int64),)
[393.71748082 393.95746107 394.28467971]
(array([ 4,  8, 11], dtype=int64),)
[394.79909458 395.02234037 395.25847384]
(array([ 3,  8, 10], dtype=int64),)
[394.79635597 395.00457937 395.24688449]
(array([ 4,  9, 11], dtype=int64),)
[396.22059815 396.27299817]
(array([6, 8], dtype=int64),)
[396.10988206 396.2627662 ]
(array([7, 9], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[402.20512379]
(array([8], dtype=int64),)
[402.20244885]
(array([9], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[402.83869188]
(array([8], dtype=int64),)
[402.7813691]
(array([9], dtype=int64),)
[402.13806395]
(array([6], dtype=int64),)
[402.0329867]
(arra

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[401.16970481]
(array([6], dtype=int64),)
[401.15217411]
(array([7], dtype=int64),)
[400.4398253  400.46313254 400.63116892]
(array([3, 5, 8], dtype=int64),)
[400.41639855 400.42483145 400.60720484]
(array([4, 6, 9], dtype=int64),)
[399.77364535 399.81116563]
(array([3, 6], dtype=int64),)
[399.73224459 399.76843143]
(array([4, 7], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[398.36708328]
(array([3], dtype=int64),)
[398.29423811]
(array([4], dtype=int64),)
[397.60958138 397.75122031]
(array([3, 9], dtype=int64),)
[397.50105063 397.71787808]
(array([ 4, 10], dtype=int64),)
[397.06001172 396.97148608 397.03417907]
(array([2, 7, 9], dtype=int64),)
[396.93031261 396.9090911  396.99541341]
(array([ 4,  8, 10], dtype=int64),)
[396.4255

[]
(array([], dtype=int64),)
[389.85726431]
(array([10], dtype=int64),)
[389.75804737]
(array([8], dtype=int64),)
[389.73671468 389.57471139]
(array([ 7, 11], dtype=int64),)
[390.42224091 389.52746667]
(array([3, 8], dtype=int64),)
[390.41740967 389.43719886 389.23589737]
(array([ 2,  7, 12], dtype=int64),)
[389.12826863]
(array([10], dtype=int64),)
[389.09132613 389.03677533]
(array([ 9, 11], dtype=int64),)
[390.16280706]
(array([1], dtype=int64),)
[388.89782375]
(array([10], dtype=int64),)
[389.76958502 389.1067478  389.01644693]
(array([ 1,  6, 10], dtype=int64),)
[389.08339703 388.93676674 389.0122651 ]
(array([ 5,  8, 11], dtype=int64),)
[389.34199695 389.0199237 ]
(array([1, 9], dtype=int64),)
[388.87145598 388.99401638]
(array([ 5, 10], dtype=int64),)
[388.66907673 388.77640827]
(array([1, 3], dtype=int64),)
[388.61284842 388.45048248]
(array([2, 4], dtype=int64),)
[387.89013132]
(array([3], dtype=int64),)
[387.82198249]
(array([5], dtype=int64),)
[386.99794101]
(array([3], dtyp

(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[318.88724232]
(array([3], dtype=int64),)
[318.78390059]
(array([4], dtype=int64),)
[320.558912]
(array([3], dtype=int64),)
[319.76573949]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[383.56873825]
(array([3], dtype=int64),)
[382.92921768]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[384.35252322]
(array([3], dtype=int64),)
[384.34610317]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[378.25837638]
(array([3], dtyp

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[390.15896887 389.85107244]
(array([3, 8], dtype=int64),)
[389.73860147 389.60065466]
(array([ 7, 12], dtype=int64),)
[389.7353146  389.27718531]
(array([3, 9], dtype=int64),)
[389.23138088 389.07705074]
(array([ 8, 10], dtype=int64),)
[385.86191975 386.13963812 385.61096506 385.69034161]
(array([1, 3, 5, 9], dtype=int64),)
[385.85607948 385.50353658 385.55012805 385.67496981]
(array([ 2,  4,  6, 10], dtype=int64),)
[384.49712387 383.88621098]
(array([2, 7], dtype=int64),)
[383.78212568 383.82085989]
(array([5, 8], dtype=int64),)
[384.42400901 383.69623741 383.74748358]
(array([3, 5, 7], dtype=int64),)
[384.34190016 383.64421932 383.67272724 383.65732529]
(array([1, 4, 6, 8], dtype=int64),)
[385.22245

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[388.9024703]
(array([3], dtype=int64),)
[388.73491323]
(array([4], dtype=int64),)
[388.82649564 388.90985964]
(array([3, 8], dtype=int64),)
[388.56675318 388.82966343]
(array([6, 9], dtype=int64),)
[387.76883032 387.38236637]
(array([3, 9], dtype=int64),)
[387.14047472 387.34308521]
(array([ 4, 10], dtype=int64),)
[386.29952865 385.69997262]
(array([ 2, 10], dtype=int64),)
[385.56777988 385.66660602]
(array([ 7, 11], dtype=int64),)
[385.77073562]
(array([3], dtype=int64),)
[385.69593154 384.51973783]
(array([ 2, 12], dtype=int64),)
[385.19474174 383.81853635]
(array([ 2, 10], dtype=int64),)
[385.11652864 383.69732796 383.62768115]
(array([ 1,  9, 12], dtype=int64),)
[383.32755613]
(array([9], dtype=int64),)
[383.31827755 383.06260341]
(array([ 8, 13], dtype=int64),)
[384.47602151 383.2

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[385.95787195]
(array([3], dtype=int64),)
[385.67013436]
(array([4], dtype=int64),)
[384.88968609]
(array([3], dtype=int64),)
[384.6376669]
(array([4], dtype=int64),)
[383.43295028 383.27475484]
(array([3, 5], dtype=int64),)
[383.12366498 383.18081482]
(array([4, 6], dtype=int64),)
[381.13336321 380.90285421]
(array([3, 7], dtype=int64),)
[380.79178492 380.86877784]
(array([4, 8], dtype=int64),)
[378.65808784 378.31428911]
(array([3, 7], dtype=int64),)
[378.14052283 378.27795051]
(array([4, 8], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[387.53073905]
(array

[382.82173923 382.54140373]
(array([3, 5], dtype=int64),)
[382.30760582 382.53467952]
(array([4, 6], dtype=int64),)
[379.52614776 379.09821091]
(array([3, 6], dtype=int64),)
[378.9620093  379.05025704]
(array([4, 7], dtype=int64),)
[375.42993719 375.13377397]
(array([3, 7], dtype=int64),)
[374.99558354 375.08949708]
(array([5, 8], dtype=int64),)
[388.20940895]
(array([3], dtype=int64),)
[388.09697746]
(array([4], dtype=int64),)
[387.11356005]
(array([4], dtype=int64),)
[387.04047317]
(array([5], dtype=int64),)
[386.46883758]
(array([3], dtype=int64),)
[386.34234671]
(array([4], dtype=int64),)
[386.75940978]
(array([3], dtype=int64),)
[386.55512256]
(array([4], dtype=int64),)
[387.27065947 387.47920165]
(array([3, 5], dtype=int64),)
[387.26263527 387.44930685]
(array([4, 6], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[388.56297562]
(array([3], dtype=int64),)
[388.51502462]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)


[387.95978508]
(array([6], dtype=int64),)
[388.41051936]
(array([5], dtype=int64),)
[388.40140583]
(array([6], dtype=int64),)
[388.47483163]
(array([3], dtype=int64),)
[388.42720628]
(array([4], dtype=int64),)
[388.69459659]
(array([3], dtype=int64),)
[388.65114322]
(array([4], dtype=int64),)
[389.00003939]
(array([3], dtype=int64),)
[388.96338528]
(array([4], dtype=int64),)
[389.52097442]
(array([3], dtype=int64),)
[389.50118053]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dt

[388.29662741]
(array([3], dtype=int64),)
[388.05683057]
(array([4], dtype=int64),)
[388.77892011]
(array([3], dtype=int64),)
[388.72080013]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[392.24761798]
(array([3], dtype=int64),)
[392.19232409]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[384.18917158 383.96142797]
(array([3, 5], dtype=int64),)
[383.88880757 383.95643775]
(array([4, 6], dtype=int64),)
[384.18394291]
(array([3], dtype=int64),)
[383.86051258]
(array([5], dtype=int64),)
[384.45453838 384.23861238]
(array([3, 5], dtype=int64),)
[383.9864131  384.23751844]
(array([4, 6], dtype=int64),)
[384.76294469]
(array([3], dtype=int64),)
[384.55339804]
(array([5], dtype=int64),)
[385.2862777]
(array([3], dtype=int64),)
[385.03427373]
(array([4], dtype=int64),)
[385.85448681 385.85281382]
(array([3, 5], dtype=int64),)
[385.64970383 385.80089469]
(array([4, 6], dtype=int64),)
[386.42057128]
(array([3], dtype=int64),)
[386.26185543]
(array([4], dtype=int64),)
[386.96563988]
(array([3], dtype=int64),)
[386.76649751]
(array([4], dtype=int64),)
[387.14466776]
(array([3], dtype=int64),)
[387.10540653]
(array([4], dtype=int64),)
[387.50534438]
(array([3], dtype=

[383.49005325]
(array([3], dtype=int64),)
[383.15263871]
(array([4], dtype=int64),)
[383.88531327]
(array([3], dtype=int64),)
[383.47146482]
(array([4], dtype=int64),)
[384.25615552 384.57043071]
(array([3, 9], dtype=int64),)
[384.01945836 384.52615547]
(array([ 4, 10], dtype=int64),)
[384.98493781]
(array([3], dtype=int64),)
[384.54604706]
(array([4], dtype=int64),)
[385.55279009]
(array([3], dtype=int64),)
[385.31092865]
(array([4], dtype=int64),)
[386.20260506]
(array([3], dtype=int64),)
[385.90622158]
(array([4], dtype=int64),)
[386.85876764]
(array([3], dtype=int64),)
[386.6024058]
(array([4], dtype=int64),)
[387.30897512]
(array([3], dtype=int64),)
[387.0788197]
(array([4], dtype=int64),)
[387.55140643]
(array([3], dtype=int64),)
[387.40924616]
(array([4], dtype=int64),)
[388.0679576]
(array([3], dtype=int64),)
[388.05956067]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([],

[389.00843472]
(array([3], dtype=int64),)
[388.88007772]
(array([4], dtype=int64),)
[389.77257002]
(array([3], dtype=int64),)
[389.61586567]
(array([4], dtype=int64),)
[390.52256376]
(array([3], dtype=int64),)
[390.40963749]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[398.43014207]
(array([3], dtype=int64),)
[398.32366803]
(array([4], dtype=int64),)
[]
(array([], dtype=int64)

[397.78573333]
(array([3], dtype=int64),)
[397.73299036]
(array([4], dtype=int64),)
[397.80592669]
(array([3], dtype=int64),)
[397.72671485]
(array([4], dtype=int64),)
[397.24943479]
(array([3], dtype=int64),)
[397.21379703]
(array([4], dtype=int64),)
[396.30756208]
(array([3], dtype=int64),)
[396.23481863]
(array([4], dtype=int64),)
[395.1201168]
(array([5], dtype=int64),)
[395.02440525]
(array([6], dtype=int64),)
[393.69667172 393.84042006 393.99146613]
(array([3, 6, 8], dtype=int64),)
[393.61014153 393.82448716 393.98747583]
(array([4, 7, 9], dtype=int64),)
[392.67835877 392.58223916]
(array([3, 6], dtype=int64),)
[392.38512709 392.5575603 ]
(array([4, 7], dtype=int64),)
[391.66099464 391.74965139]
(array([3, 9], dtype=int64),)
[391.42573861 391.73882015]
(array([ 5, 10], dtype=int64),)
[391.06039682]
(array([2], dtype=int64),)
[390.70813055]
(array([4], dtype=int64),)
[390.56018868 390.60605244 390.26026112]
(array([1, 3, 8], dtype=int64),)
[390.55318369 390.12832477 390.20637822]


[388.29049357]
(array([1], dtype=int64),)
[387.65733563]
(array([8], dtype=int64),)
[386.75682404 386.83628049]
(array([6, 8], dtype=int64),)
[386.69080065 386.74649892 386.76367343]
(array([5, 7, 9], dtype=int64),)
[386.49424842]
(array([1], dtype=int64),)
[385.75088709]
(array([5], dtype=int64),)
[385.73398138 385.08010745]
(array([3, 5], dtype=int64),)
[385.60170622 385.00699737 385.07696036]
(array([1, 4, 6], dtype=int64),)
[385.30661669 385.36748059]
(array([1, 3], dtype=int64),)
[385.18891485 384.60811519]
(array([2, 5], dtype=int64),)
[385.31382162 384.76699287]
(array([3, 5], dtype=int64),)
[385.21740153 384.60799789 384.5975886 ]
(array([2, 4, 7], dtype=int64),)
[385.68072126 384.86370173]
(array([2, 7], dtype=int64),)
[385.6010756  384.85967205 384.79464293]
(array([1, 6, 8], dtype=int64),)
[385.11178134]
(array([9], dtype=int64),)
[384.98262322 385.06947168]
(array([ 7, 10], dtype=int64),)
[385.26213761]
(array([9], dtype=int64),)
[385.04594475 385.22086921]
(array([ 6, 10],

(array([4, 7], dtype=int64),)
[386.16248456 385.4357704 ]
(array([3, 9], dtype=int64),)
[386.08932811 385.39937853 385.39222407]
(array([ 2,  7, 10], dtype=int64),)
[386.23776333 385.44517428]
(array([3, 6], dtype=int64),)
[386.17112471 385.37676541 385.43990843]
(array([2, 5, 7], dtype=int64),)
[385.20821312]
(array([8], dtype=int64),)
[385.10713878 385.14934883]
(array([6, 9], dtype=int64),)
[385.62879612]
(array([2], dtype=int64),)
[385.60513724 384.74087044]
(array([1, 6], dtype=int64),)
[385.27990038 384.5359458 ]
(array([2, 7], dtype=int64),)
[385.24757888 384.43051683 384.48060449]
(array([1, 6, 8], dtype=int64),)
[385.21936993]
(array([3], dtype=int64),)
[385.051283   384.33407616]
(array([2, 4], dtype=int64),)
[385.44680572 384.81181269]
(array([3, 9], dtype=int64),)
[385.27106051 384.65606327 384.79816714]
(array([ 2,  4, 10], dtype=int64),)
[385.84770766 385.1475689  385.34092618]
(array([2, 5, 8], dtype=int64),)
[385.78911191 385.13761958 385.08252254 385.30687872]
(array([

(array([1, 5], dtype=int64),)
[383.89618025 383.90627297]
(array([4, 6], dtype=int64),)
[384.94664007 384.14641184 384.29779298]
(array([1, 6, 8], dtype=int64),)
[384.04582106 384.08460751 384.17644091]
(array([5, 7, 9], dtype=int64),)
[]
(array([], dtype=int64),)
[384.31446542]
(array([6], dtype=int64),)
[]
(array([], dtype=int64),)
[384.56073315]
(array([5], dtype=int64),)
[385.5922045  384.98685873]
(array([3, 8], dtype=int64),)
[385.55067178 384.80985888 384.95423616]
(array([2, 5, 9], dtype=int64),)
[386.1359653  385.26248181]
(array([1, 6], dtype=int64),)
[385.25574571 385.19417284]
(array([5, 7], dtype=int64),)
[386.27621171 385.50443369]
(array([1, 8], dtype=int64),)
[385.38784575 385.45961353]
(array([7, 9], dtype=int64),)
[385.97806815 385.41964801 385.44975633]
(array([3, 7, 9], dtype=int64),)
[385.17561596 385.38460385 385.44132278]
(array([ 5,  8, 10], dtype=int64),)
[386.13880521]
(array([2], dtype=int64),)
[385.61959332]
(array([6], dtype=int64),)
[384.17181386 384.04103

[386.41489931]
(array([8], dtype=int64),)
[386.3225398  385.93413237]
(array([ 7, 13], dtype=int64),)
[]
(array([], dtype=int64),)
[384.87747775]
(array([13], dtype=int64),)
[]
(array([], dtype=int64),)
[382.98821907]
(array([13], dtype=int64),)
[]
(array([], dtype=int64),)
[380.9351173]
(array([13], dtype=int64),)
[]
(array([], dtype=int64),)
[379.30565385]
(array([13], dtype=int64),)
[]
(array([], dtype=int64),)
[378.85423834]
(array([14], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[375.20240861]
(array([3], dtype=int64),)
[374.7311993]
(array([4], dtype=int64),)
[367.32917108]
(array([2], dtype=int64),)
[367.295

[381.98061889]
(array([3], dtype=int64),)
[381.61506129]
(array([4], dtype=int64),)
[381.47734258]
(array([3], dtype=int64),)
[380.92006994]
(array([4], dtype=int64),)
[380.80371275 380.74558751]
(array([3, 8], dtype=int64),)
[380.22849405 380.68392519]
(array([4, 9], dtype=int64),)
[380.12608768]
(array([3], dtype=int64),)
[379.66746955]
(array([4], dtype=int64),)
[379.33533718 379.61818742]
(array([3, 8], dtype=int64),)
[378.98950209 379.60271454]
(array([4, 9], dtype=int64),)
[378.12730813]
(array([3], dtype=int64),)
[377.74481188]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[380.83174666]
(array([3], dtype=int64),)
[380.81484434]
(array([4], dtype=int64),)
[383.68225979]
(array([3], dtype=int64),)
[383.64236568]
(array([4], dtype=int64),)
[385.71489068]
(array([3], dtype

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[385.72603614]
(array([2], dtype=int64),)
[385.62029377]
(array([4], dtype=int64),)
[386.47536142]
(array([3], dtype=int64),)
[386.1383519]
(array([4], dtype=int64),)
[387.65671832]
(array([3], dtype=int64),)
[387.3873561]
(array([4], dtype=int64),)
[389.54121101 389.81072726]
(array([3, 7], dtype=int64),)
[389.34423851 389.77418324]
(array([4, 8], dtype=int64),)
[391.40952976]
(array([3], dtype=int64),)
[391.33466213]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[393.20372842]
(array([3], dtype=int64),)
[393.17096261]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[390.7047614]
(array([3], dtype=int64),)
[390.67600238]
(array([4], dtype=int64),)
[390.13745914]
(array([3], dtype=in

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[389.7142244]
(array([3], dtype=int64),)
[389.67320329]
(array([4], dtype=int64),)
[389.4845394]
(array([3], dtype=int64),)
[389.47741491]
(array([4], dtype=int64),)
[389.28699424]
(array([3], dtype=int64),)
[389.23824217]
(array([4], dtype=int64),)
[389.00976364]
(array([3], dtype=int64),)
[388.92820944]
(array([4], dtype=int64),)
[388.78278435]
(array([3], dtype=int64),)
[388.67939888]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[388.43784253]
(array([3], dtype=int64),)
[388.30236451]
(array([4], dtype=int64),)
[388.16173529]
(array([3], dtype=int64),)
[388.00518499]
(array([4], dtype=int64),)
[387.66223342]
(array([3], dtype=int64),)
[387.48056682]
(array([4

[387.12826981]
(array([3], dtype=int64),)
[387.04122607]
(array([4], dtype=int64),)
[386.63837647]
(array([3], dtype=int64),)
[386.35201057]
(array([4], dtype=int64),)
[386.23425335]
(array([3], dtype=int64),)
[386.01087761]
(array([4], dtype=int64),)
[385.96627939]
(array([3], dtype=int64),)
[385.70120238]
(array([4], dtype=int64),)
[386.13409158]
(array([3], dtype=int64),)
[385.76061649]
(array([4], dtype=int64),)
[386.35212467 386.56537407]
(array([3, 7], dtype=int64),)
[386.0251463  386.56307914]
(array([4, 8], dtype=int64),)
[386.6270018  386.46451108]
(array([3, 5], dtype=int64),)
[386.17022808 386.41972314]
(array([4, 6], dtype=int64),)
[386.84907511]
(array([3], dtype=int64),)
[386.51675543]
(array([4], dtype=int64),)
[387.19240409]
(array([2], dtype=int64),)
[386.82909244]
(array([5], dtype=int64),)
[387.79652393]
(array([3], dtype=int64),)
[387.35346979]
(array([5], dtype=int64),)
[388.30117946]
(array([2], dtype=int64),)
[387.83536218]
(array([4], dtype=int64),)
[388.6664754

[387.97124527 387.99654453]
(array([3, 7], dtype=int64),)
[387.57556126 387.96174137]
(array([5, 8], dtype=int64),)
[388.59491738]
(array([3], dtype=int64),)
[388.18333486]
(array([4], dtype=int64),)
[388.97867762]
(array([2], dtype=int64),)
[388.53798119]
(array([4], dtype=int64),)
[389.08709196]
(array([3], dtype=int64),)
[388.55474039]
(array([4], dtype=int64),)
[388.67629449 388.40382454]
(array([3, 7], dtype=int64),)
[388.18168694 388.29826092]
(array([4, 8], dtype=int64),)
[388.00860774]
(array([3], dtype=int64),)
[387.90760527 387.44550967]
(array([2, 5], dtype=int64),)
[387.34285544 386.63382696]
(array([3, 8], dtype=int64),)
[387.29666403 386.46467065 386.4676427 ]
(array([1, 7, 9], dtype=int64),)
[386.64335858 385.8300664  385.8055177 ]
(array([3, 6, 9], dtype=int64),)
[386.60039613 385.80871528 385.6540495  385.7110343 ]
(array([ 2,  5,  8, 10], dtype=int64),)
[385.04853325]
(array([8], dtype=int64),)
[385.02330639 384.88181192]
(array([ 7, 10], dtype=int64),)
[384.39973539 

[]
(array([], dtype=int64),)
[383.83297291]
(array([13], dtype=int64),)
[383.11369499 382.85833861]
(array([ 9, 12], dtype=int64),)
[383.03145923 382.82145202 382.76183143]
(array([ 8, 11, 13], dtype=int64),)
[383.60847954]
(array([2], dtype=int64),)
[383.59575049 381.93543856]
(array([ 1, 11], dtype=int64),)
[381.91010802]
(array([7], dtype=int64),)
[381.83241182 381.55020095]
(array([ 6, 12], dtype=int64),)
[381.86495697]
(array([12], dtype=int64),)
[381.83130536 381.84328703]
(array([11, 13], dtype=int64),)
[383.17679321 382.95457822]
(array([5, 7], dtype=int64),)
[383.13611401 382.88446872 382.53750127]
(array([ 4,  6, 12], dtype=int64),)
[384.95733598]
(array([3], dtype=int64),)
[384.84728816 383.40549196]
(array([ 2, 12], dtype=int64),)
[385.63346161 384.23161679]
(array([ 2, 10], dtype=int64),)
[385.58930307 384.20318047 384.13703064]
(array([ 1,  9, 12], dtype=int64),)
[387.17833394]
(array([3], dtype=int64),)
[385.30834712]
(array([13], dtype=int64),)
[388.71882256]
(array([8]

(array([ 8, 14], dtype=int64),)
[390.32819009]
(array([10], dtype=int64),)
[388.20964884]
(array([15], dtype=int64),)
[385.46727426]
(array([1], dtype=int64),)
[383.35874094]
(array([12], dtype=int64),)
[379.89662042]
(array([3], dtype=int64),)
[378.75031209]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[379.36738225]
(array([3], dtype=int64),)
[391.316544]
(array([1], dtype=int64),)
[389.11389638]
(array([14], dtype=int64),)
[391.96725017]
(array([1], dtype=int64),)
[389.60935467]
(array([14], dtype=int64),)
[]
(array([], dtype=int64),)
[389.01420398]
(array([14], dtype=int64),)
[]
(array([], dtype=int64),)
[387.96485092]
(array([14], dtype=int64),)
[389.58843705]
(array([1], dtype=int64),)
[386.66364659]
(array([14], dtype=int64),)
[388.07974686]
(array([1], dtype=int64),)
[385.40564044]
(array([14], dtype=int64),)
[387.03151516]
(array([2], dtype=int64),)
[384.17616463]
(array([14], dtype=int64),)
[386.20181616]
(array([3], dtype=int64),)
[383.17266496]
(array([15], dtype

[391.16109362 389.58047717]
(array([2, 9], dtype=int64),)
[391.03968372 389.57246609 388.30006257]
(array([ 1,  8, 14], dtype=int64),)
[389.17423108]
(array([1], dtype=int64),)
[386.55477259]
(array([14], dtype=int64),)
[387.10064446]
(array([2], dtype=int64),)
[384.42127312]
(array([14], dtype=int64),)
[384.84728044]
(array([4], dtype=int64),)
[382.40310825]
(array([14], dtype=int64),)
[373.77816402]
(array([2], dtype=int64),)
[373.71802616 373.12112767]
(array([1, 6], dtype=int64),)
[369.37951677]
(array([3], dtype=int64),)
[368.52685789]
(array([4], dtype=int64),)
[376.29325163]
(array([3], dtype=int64),)
[376.11450501]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int

(array([3], dtype=int64),)
[383.59642529]
(array([4], dtype=int64),)
[382.66954678]
(array([3], dtype=int64),)
[382.53961801]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[377.84985781]
(array([3], dtype=int64),)
[377.23731661]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[371.59636271]
(array([1], dtype=int64),)
[378.27705335]
(array([7], dtype=int64),)
[377.79465736]
(array([13], dtype=int64),)
[369.03323526]
(array([3], dtype=int64),)
[368.14702566]
(array([12], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[365.68248143]
(array([2], dtype=int64),)
[365.67941913]
(array([3], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]


[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[359.14579341 359.28457672 359.34341673 359.38684305]
(array([ 2,  4,  7, 10], dtype=int64),)
[358.99847715 359.1734381  359.28719096 359.3095588 ]
(array([ 3,  5,  8, 12], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[331.45397283]
(array([3], dtype=int64),)
[331.32772952]
(

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[320.90695096]
(array([3], dtype=int64),)
[319.99995506]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[330.91945455]
(array([3], dtype=int64),)
[329.11292545]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[388.69529993]
(array([3], dtype=int64),)
[388.60289132]
(array([4], dtype=int64),)
[388.12276943]
(array([3], dtype=int64),)
[387.96380475]
(array([4], dtype=int64),)
[386.99625985]
(array([3], dtype=int64),)
[386.74312742]
(array([4], dtype=int64),)
[386.05989364]
(array([3], dtype=int64),)
[385.80893204]
(array([4], dtype=int64),)
[385.69750989]
(array([3], dtype=int64),)
[385.67044809]
(array([4], dtype=int64),)
[385.6

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[388.46016104]
(array([3], dtype=int64),)
[388.33337584]
(array([4], dtype=int64),)
[387.8491461]
(array([3], dtype=int64),)
[387.72866167]
(array([4], dtype=int64),)
[386.77475612]
(array([3], dtype=int64),)
[386.64229024]
(array([4], dtype=int64),)
[385.84794878]
(array([3], dtype=int64),)
[385.6217405]
(array([4], dtype=int64),)
[385.49968755]
(array([3], dtype=int64),)
[385.42200351]
(array([4], dtype=int64),)
[385.36959198]
(array([3], dtype=int64),)
[385.09615329]
(array([4], dtype=int64),)
[385.31558311]
(array([3], dtype=int64),)
[385.19430662]
(array([4], dtype=int64),)
[385.44691026]
(array([3], dtype=int64),)
[385.31533554]
(array([4], dtype=int64),)
[385.6789758]
(array([3], dtype=int64),)
[385.5355292]
(array([4], dtype=int64),)
[386.0671408]
(array([3], dtype=int64),)
[385

[384.78431156]
(array([3], dtype=int64),)
[384.51338123]
(array([4], dtype=int64),)
[384.71858676]
(array([3], dtype=int64),)
[384.59546248]
(array([4], dtype=int64),)
[384.92282114]
(array([3], dtype=int64),)
[384.7137765]
(array([4], dtype=int64),)
[385.10961281]
(array([3], dtype=int64),)
[384.87471828]
(array([4], dtype=int64),)
[385.46523739]
(array([3], dtype=int64),)
[385.31065044]
(array([4], dtype=int64),)
[385.96231025]
(array([3], dtype=int64),)
[385.64196298]
(array([4], dtype=int64),)
[386.38545762]
(array([3], dtype=int64),)
[386.22445226]
(array([4], dtype=int64),)
[387.13260022]
(array([3], dtype=int64),)
[386.9053793]
(array([4], dtype=int64),)
[387.84494467]
(array([3], dtype=int64),)
[387.62560048]
(array([4], dtype=int64),)
[388.41673046]
(array([3], dtype=int64),)
[388.20099911]
(array([4], dtype=int64),)
[388.68403968]
(array([3], dtype=int64),)
[388.4587407]
(array([4], dtype=int64),)
[388.44576345 388.62635465]
(array([1, 3], dtype=int64),)
[388.4361833  388.452

[389.32380706 389.46261326]
(array([3, 6], dtype=int64),)
[389.08217459 389.44689315]
(array([4, 7], dtype=int64),)
[388.95079862]
(array([3], dtype=int64),)
[388.66970757]
(array([4], dtype=int64),)
[388.08969369 388.30126006 388.13042932]
(array([1, 3, 5], dtype=int64),)
[388.08898128 387.9649577  388.04131246]
(array([2, 4, 6], dtype=int64),)
[387.52657335 387.16750554]
(array([3, 5], dtype=int64),)
[387.12816199 387.12858769]
(array([4, 6], dtype=int64),)
[386.75565746 386.85188859 386.50859705 386.6220937 ]
(array([1, 3, 6, 9], dtype=int64),)
[386.69387755 386.31676852 386.44759333 386.59727726]
(array([ 2,  5,  7, 10], dtype=int64),)
[386.50945978 386.50850814 386.10334385]
(array([1, 3, 8], dtype=int64),)
[386.47788188 385.91293135 385.9556231 ]
(array([2, 7, 9], dtype=int64),)
[386.54982731]
(array([3], dtype=int64),)
[385.90367258]
(array([7], dtype=int64),)
[386.78324172 386.24546355 386.31793358]
(array([2, 6, 9], dtype=int64),)
[386.69811599 386.1840834  386.13620556 386.24

[386.6564492  386.62617357 386.13741321]
(array([1, 3, 6], dtype=int64),)
[386.61095093 386.09409827 385.90380436]
(array([ 2,  4, 11], dtype=int64),)
[386.45333373 386.41426047 385.98246589 385.76311554 385.66746235]
(array([ 1,  3,  5,  7, 11], dtype=int64),)
[386.40285966 385.97715364 385.73566995 385.64600298 385.57491107]
(array([ 2,  4,  6, 10, 12], dtype=int64),)
[386.07821418 385.41827606 385.23577872]
(array([ 3,  8, 11], dtype=int64),)
[385.3937093  385.23520045 385.11925998]
(array([ 7, 10, 12], dtype=int64),)
[385.72574499 384.8178204  384.67495432]
(array([ 1, 10, 12], dtype=int64),)
[384.76888091 384.66483275 384.60579893]
(array([ 8, 11, 13], dtype=int64),)
[385.26025442 384.35171082]
(array([3, 9], dtype=int64),)
[384.25738842 383.98585745]
(array([ 8, 13], dtype=int64),)
[384.84319739]
(array([2], dtype=int64),)
[383.38709543]
(array([13], dtype=int64),)
[384.92095855]
(array([3], dtype=int64),)
[382.43942914]
(array([14], dtype=int64),)
[384.88127421]
(array([3], dtyp

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[379.81868212]
(array([3], dtype=int64),)
[378.86867404]
(array([4], dtype=int64),)
[380.8147667]
(array([2], dtype=int64),)
[379.69177443]
(array([4], dtype=int64),)
[381.98879638 381.51741111]
(array([3, 9], dtype=int64),)
[381.14167067 381.44279828]
(array([ 5, 10], dtype=int64),)
[381.72967713]
(array([3], dtype=int64),)
[380.92536966]
(array([4], dtype=int64),)
[381.68323321]
(array([3], dtype=int64),)
[381.08884631]
(array([4], dtype=int64),)
[383.1229365  383.19657488 383.28527894]
(array([4, 6, 9], dtype=int64),)
[383.06829554 383.07638077 383.19575517]
(array([ 5,  7, 10], dtype=int64),)
[384.26486872]
(array([10], dtype=int64),)
[384.23268214]
(array([11], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=

(array([5], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[358.61980858]
(array([3], dtype=int64),)
[358.0854364]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[362.34510191]
(array([3], dtype=int64),)
[362.14758533]
(array([4], dtype=int64),)
[362.25097931]
(array([3], dtype=int64),)
[361.91386254]
(array([4], dtype=int64),)
[364.61637258]
(array([3],

[380.34340801]
(array([3], dtype=int64),)
[380.29164057]
(array([4], dtype=int64),)
[380.20604631]
(array([3], dtype=int64),)
[380.0819204]
(array([4], dtype=int64),)
[380.1161077]
(array([3], dtype=int64),)
[379.98547846]
(array([4], dtype=int64),)
[380.12134325]
(array([3], dtype=int64),)
[379.97768713]
(array([4], dtype=int64),)
[380.2547307]
(array([3], dtype=int64),)
[380.10000792]
(array([4], dtype=int64),)
[380.54482753]
(array([3], dtype=int64),)
[380.29600444]
(array([4], dtype=int64),)
[380.94522052]
(array([3], dtype=int64),)
[380.86258288]
(array([4], dtype=int64),)
[381.6651298]
(array([3], dtype=int64),)
[381.43894614]
(array([4], dtype=int64),)
[382.47377343]
(array([3], dtype=int64),)
[382.35988803]
(array([4], dtype=int64),)
[383.43192083]
(array([3], dtype=int64),)
[383.34067124]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[386.04248735]
(array([3], dtype=int64),)
[385.89638081]
(array([4], dtype=int64),)
[]
(array([], dtype=in

[390.24110174]
(array([3], dtype=int64),)
[390.21240647]
(array([4], dtype=int64),)
[390.18878079]
(array([3], dtype=int64),)
[390.14055563]
(array([4], dtype=int64),)
[389.61861398]
(array([3], dtype=int64),)
[389.52393028]
(array([4], dtype=int64),)
[388.97283888]
(array([3], dtype=int64),)
[388.93719178]
(array([4], dtype=int64),)
[388.27814581]
(array([3], dtype=int64),)
[388.09384795]
(array([4], dtype=int64),)
[387.87635708 387.90018365]
(array([3, 6], dtype=int64),)
[387.60773596 387.83807968]
(array([4, 7], dtype=int64),)
[387.62056667 387.77876088 387.65820786]
(array([1, 3, 8], dtype=int64),)
[387.56246718 387.38507573 387.63859133]
(array([2, 4, 9], dtype=int64),)
[387.58854299 387.15242939]
(array([2, 5], dtype=int64),)
[387.10127178 387.01004445]
(array([4, 8], dtype=int64),)
[387.16091668 386.02641036]
(array([ 3, 12], dtype=int64),)
[387.08935963 385.98987092 386.02611322]
(array([ 2, 11, 13], dtype=int64),)
[385.82751488 385.0319476  384.67633239 384.46228629]
(array([ 

(array([2, 8], dtype=int64),)
[375.21921319 375.26535144]
(array([6, 9], dtype=int64),)
[375.77840986 375.29436317]
(array([2, 5], dtype=int64),)
[375.18457961 375.15457355]
(array([4, 6], dtype=int64),)
[380.18616014]
(array([8], dtype=int64),)
[379.79810998]
(array([13], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[366.70686026]
(array([3], dtype=int64),)
[366.53497713]
(array([4], dtype=int64),)
[373.39837138]
(array([3], dtype=int64),)
[373.20432918]
(array([4], dtype=int64),)
[380.25599518]
(array([8], dtype=int64),)
[379.75401772]
(array([14], dtype=int64),)
[380.52641925]
(array([10], dtype=int64),)
[379.60404216]
(array([14], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[369.38110152]
(array([3], dtype=int64),)
[369.33846055]
(array([4], dtype=int64),

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], 

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[325.79480412]
(array([3], dtype=int64),)
[325.02488753]
(array([4], dtype=int64),)
[313.50641401]
(array([3], dtype=int64),)
[311.95172736]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[379.20075948]
(array([3], dtype=int64),)
[379.19312909]
(array([4], dtype=int64),)
[380.49854784]
(array([3], dtype=int64),)
[380.14011074]
(array([4], dtype=int64),)
[379.66186966]
(array([3], dtype=int64),)
[379.44934784]
(array([4], dtype=int64),)
[378.3602303]
(array([3], dtype=int64),)
[378.24493478]
(array([4], dtype=int64),)
[377.66125271]
(array([3], dtype=int64),)
[377.59744633]
(array([4], dtype=int64),)
[377.21223431]
(array([3], dtype=int64),)
[377.2122305]
(array([4

[372.27327271]
(array([3], dtype=int64),)
[371.96366844]
(array([4], dtype=int64),)
[372.42223796]
(array([3], dtype=int64),)
[372.20580918]
(array([4], dtype=int64),)
[372.84789242]
(array([3], dtype=int64),)
[372.56298953]
(array([4], dtype=int64),)
[373.34507045]
(array([3], dtype=int64),)
[373.32245855]
(array([4], dtype=int64),)
[374.0090924]
(array([3], dtype=int64),)
[373.83381252]
(array([4], dtype=int64),)
[374.59721255]
(array([3], dtype=int64),)
[374.5810947]
(array([4], dtype=int64),)
[375.40897749]
(array([3], dtype=int64),)
[375.14785356]
(array([4], dtype=int64),)
[376.21864559]
(array([3], dtype=int64),)
[376.04604221]
(array([4], dtype=int64),)
[377.0256729]
(array([3], dtype=int64),)
[376.93430194]
(array([4], dtype=int64),)
[378.05041236]
(array([3], dtype=int64),)
[377.89610407]
(array([4], dtype=int64),)
[379.06124366]
(array([3], dtype=int64),)
[379.00837926]
(array([4], dtype=int64),)
[380.11734208]
(array([3], dtype=int64),)
[379.99864786]
(array([4], dtype=int6

(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[379.45272707]
(array([8], dtype=int64),)
[379.43886999]
(array([9], dtype=int64),)
[379.61939448]
(array([8], dtype=int64),)
[379.53548403]
(array([10], dtype=int64),)
[377.90999911 377.86700548]
(array([6, 8], dtype=int64),)
[377.83931413 377.82200168]
(array([7, 9], dtype=int64),)
[375.56481009 375.82948203]
(array([3, 9], dtype=int64),)
[375.4589321  375.82060517]
(array([ 4, 10], dtype=int64),)
[374.48112137 374.29716332]
(array([3, 5], dtype=int64),)
[374.26624788 374.2639674 ]
(array([4, 6], dtype=int64),)
[374.35319938]
(array([3], dtype=int64),)
[374.044662]
(array([4], dtype=int64),)
[374.23166635]
(array([3], dtype=int64),)
[373.82559717]
(array([4], dtype=int64),)
[374.07649769 374.01368721]
(array([3, 5], dtype=int64),)
[373.87645546 373.91374369]
(array([4, 6], dtype=int64),)
[373.92777717 374.19531617 373.96657091]
(array([1, 3, 5], dtype=int64),)
[373.92121487 373.82376422 373.8624716 ]

[372.83490028 372.96899547 372.59165313 372.82007281]
(array([1, 3, 5, 7], dtype=int64),)
[372.76610467 372.53651224 372.57159071 372.73654333]
(array([2, 4, 6, 8], dtype=int64),)
[373.26204434 372.94338764 373.08026428]
(array([2, 5, 7], dtype=int64),)
[372.71889202 372.92170626 372.91317163]
(array([4, 6, 8], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(a

[375.75791918]
(array([3], dtype=int64),)
[375.74430812]
(array([4], dtype=int64),)
[375.10603379]
(array([3], dtype=int64),)
[375.0805533]
(array([4], dtype=int64),)
[374.41386079]
(array([3], dtype=int64),)
[374.3755276]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[373.00076908]
(array([3], dtype=int64),)
[372.8611752]
(array([4], dtype=int64),)
[372.08470051]
(array([3], dtype=int64),)
[372.07184811]
(array([4], dtype=int64),)
[371.49398377]
(array([3], dtype=int64),)
[371.39368587]
(array([4], dtype=int64),)
[371.13797159]
(array([3], dtype=int64),)
[370.95595046]
(array([4], dtype=int64),)
[370.90976366]
(array([3], dtype=int64),)
[370.79253627]
(array([4], dtype=int64),)
[370.99794722]
(array([3], dtype=int64),)
[370.87351121]
(array([4], dtype=int64),)
[371.22520864]
(array([3], dtype=int64),)
[371.16679131]
(array([4], dtype=int64),)
[371.74343874]
(array([3], dtype=int64),)
[371.60879341]
(array([4], dtype=int64),)
[372.35611821]
(array

(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[380.27970047]
(array([3], dtype=int64),)
[380.2699927]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[383.69449974]
(array([3], dtype=int64),)
[383.68350924]
(array([4], dtype=int64),)
[383.63356281 383.74329545]
(array([3, 5], dtype=int64),)
[383.55258578 383.68007118]
(array([4, 6], dtype=int64),)
[382.91495316 382.76944338]
(array([3, 5], dtype=int64),)
[382.65245669 382.72148641]
(array([4, 6], dtype=int64),)
[381.03731364]
(array([2

[368.7191548]
(array([2], dtype=int64),)
[368.34329672]
(array([4], dtype=int64),)
[368.37646508]
(array([3], dtype=int64),)
[367.85856973]
(array([4], dtype=int64),)
[368.14576891]
(array([3], dtype=int64),)
[367.61674245]
(array([4], dtype=int64),)
[367.82333226]
(array([3], dtype=int64),)
[367.34259234]
(array([4], dtype=int64),)
[367.79081694 367.86898248]
(array([3, 9], dtype=int64),)
[367.42658757 367.13715697 367.84226635]
(array([ 1,  4, 10], dtype=int64),)
[367.79214061 367.45130371]
(array([3, 5], dtype=int64),)
[367.28376717 367.37306736]
(array([4, 6], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(arra

[]
(array([], dtype=int64),)
[373.77466114]
(array([3], dtype=int64),)
[373.65168211]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[371.99210949]
(array([3], dtype=int64),)
[371.92303718]
(array([4], dtype=int64),)
[371.43389435]
(array([3], dtype=int64),)
[371.34223929]
(array([4], dtype=int64),)
[371.06165383]
(array([3], dtype=int64),)
[370.9452972]
(array([4], dtype=int64),)
[370.91800132]
(array([3], dtype=int64),)
[370.78059754]
(array([4], dtype=int64),)
[371.0175144]
(array([3], dtype=int64),)
[370.95538872]
(array([4], dtype=int64),)
[371.30317836]
(array([3], dtype=int64),)
[371.1525233]
(array([4], dtype=int64),)
[371.7415009]
(array([3], dtype=int64),)
[371.68237311]
(array([4], dtype=int64),)
[372.31771309]
(array([3], dtype=int64),)
[372.18682495]
(array([4], dtype=int64),)
[373.09840928]
(array([3], dtype=int64),)
[372.99286051]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[375.21318067]
(arr

[377.06720568]
(array([4], dtype=int64),)
[374.93777519]
(array([3], dtype=int64),)
[374.76216146]
(array([4], dtype=int64),)
[371.21601937]
(array([3], dtype=int64),)
[370.76598862]
(array([4], dtype=int64),)
[366.37765989]
(array([3], dtype=int64),)
[365.94613477]
(array([4], dtype=int64),)
[361.74732321]
(array([3], dtype=int64),)
[361.66798122]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[326.6679881]
(array([3], dtype=int64),)
[325.95131907]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[350.25255435]
(array([3], dtype=int64),)
[349.78621153]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[371.70164891 371.49297507 371.56885156]
(array([

(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[336.33533887]
(array([3], dtype=int64),)
[336.22978457]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[317.91726397]
(array([3], dtype=int64),)
[317.63092231]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int

[372.40821043]
(array([4], dtype=int64),)
[372.9299655]
(array([3], dtype=int64),)
[372.74690895]
(array([4], dtype=int64),)
[373.29546012]
(array([3], dtype=int64),)
[373.06787897]
(array([4], dtype=int64),)
[373.47438105]
(array([3], dtype=int64),)
[373.2821498]
(array([4], dtype=int64),)
[373.59588297]
(array([3], dtype=int64),)
[373.44640848]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[373.47447401]
(array([3], dtype=int64),)
[373.46769204]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[372.84527733]
(array([3], dtype=int64),)
[372.81383526]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[372.33351871]
(array([3], dtype=int64),)
[372.28728588]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[371.79923353]
(array([3], dtype=int64),)
[371.76757993]
(array([4], dtype=int64),

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[367.52333285]
(array([3], dtype=int64),)
[367.33383992]
(array([4], dtype=int64),)
[367.31538947]
(array([3], dtype=int64),)
[366.97959881]
(array([4], dtype=int64),)
[366.94628458]
(array([3], dtype=int64),)
[366.70576331]
(array([4], dtype=int64),)
[366.42956759]
(array([3], dtype=int64),)
[366.19848058]
(array([4], dtype=int64),)
[365.72462693]
(array([3], dtype=int64),)
[365.53925012]
(array([4], dtype=int64),)
[365.0508865  364.98016879]
(array([3, 5], dtype=int64),)


[335.37198673]
(array([3], dtype=int64),)
[335.12066312]
(array([4], dtype=int64),)
[340.40791617]
(array([3], dtype=int64),)
[339.53290022]
(array([4], dtype=int64),)
[348.57943255]
(array([3], dtype=int64),)
[348.51629086]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[368.62056163]
(array([3], dtype=int64),)
[368.53428546]
(array([4], dtype=int64),)
[369.17782606]
(array([3], dtype=int64),)
[369.16957682]
(array([4], dtype=int64),)
[369.61096036]
(array([3], dtype=int64),)
[369.56438603]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[370.14245041]
(array([3], dtype=int64),)
[370.09013798]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[370.27064637]
(array([3], dtype=int64),)
[370.17908584]
(array(

[369.93291425]
(array([4], dtype=int64),)
[369.67613121]
(array([3], dtype=int64),)
[369.50054077]
(array([4], dtype=int64),)
[369.21869408]
(array([3], dtype=int64),)
[369.12637411]
(array([4], dtype=int64),)
[368.93277783]
(array([3], dtype=int64),)
[368.84423956]
(array([4], dtype=int64),)
[368.70300718]
(array([3], dtype=int64),)
[368.70017607]
(array([4], dtype=int64),)
[368.55930308]
(array([3], dtype=int64),)
[368.55285562]
(array([4], dtype=int64),)
[368.53295375]
(array([3], dtype=int64),)
[368.43024194]
(array([4], dtype=int64),)
[368.54044626]
(array([3], dtype=int64),)
[368.48061894]
(array([4], dtype=int64),)
[368.74651944]
(array([3], dtype=int64),)
[368.57363883]
(array([4], dtype=int64),)
[368.83198814]
(array([3], dtype=int64),)
[368.69952149]
(array([4], dtype=int64),)
[368.6815994]
(array([3], dtype=int64),)
[368.4991776]
(array([4], dtype=int64),)
[368.29985021]
(array([3], dtype=int64),)
[368.1734549]
(array([4], dtype=int64),)
[367.79235603]
(array([3], dtype=int6

[366.7904512]
(array([3], dtype=int64),)
[366.37670896]
(array([4], dtype=int64),)
[366.5399647]
(array([3], dtype=int64),)
[366.1397955]
(array([4], dtype=int64),)
[366.0972473]
(array([3], dtype=int64),)
[365.61945626]
(array([4], dtype=int64),)
[365.18175423 365.52217911]
(array([1, 3], dtype=int64),)
[365.11604037 365.03871621]
(array([2, 4], dtype=int64),)
[364.90517329]
(array([3], dtype=int64),)
[364.49031814]
(array([4], dtype=int64),)
[364.27050672]
(array([3], dtype=int64),)
[363.67978922]
(array([4], dtype=int64),)
[363.44192527]
(array([3], dtype=int64),)
[362.88476242]
(array([4], dtype=int64),)
[362.76291807]
(array([3], dtype=int64),)
[362.17309168]
(array([4], dtype=int64),)
[362.23549608]
(array([3], dtype=int64),)
[361.70020095]
(array([4], dtype=int64),)
[362.07396247]
(array([3], dtype=int64),)
[361.53462196]
(array([4], dtype=int64),)
[362.00992574]
(array([3], dtype=int64),)
[361.31014618]
(array([4], dtype=int64),)
[361.85105084]
(array([3], dtype=int64),)
[361.1

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[351.24989837]
(array([3], dtype=int64),)
[351.22978651]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[352.67510053]
(array([3], dtype=int64),)
[352.60389358]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[353.05574244]
(array([3], dtype=int64),)
[353.03805533]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int

[368.82440674]
(array([3], dtype=int64),)
[368.60979206]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[368.66931851]
(array([3], dtype=int64),)
[368.57453906]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[367.04010203]
(array([3], dtype=int64),)
[366.96718393]
(array([4], dtype=int64),)
[366.02689431]
(array([3], dtype=int64),)
[365.89545147]
(array([4], dtype=int64),)
[365.33818979]
(array([3], dtype=int64),)
[365.24194693]
(array([4], dtype=int64),)
[365.18052012]
(array([3], dtype=int64),)
[364.91146702]
(array([4], dtype=int64),)
[365.02321048]
(array([3], dtype=int64),)
[364.79967553]
(array([4], dtype=int64),)
[365.00360945]
(array([3], dtype=int64),)
[364.829291]
(array([4], dtype=int64),)
[365.16711995]
(array([3], dtype=int64),)
[364.8188729]
(array([4], dtype=int64),)
[365.18032607]
(array([3], dtype=int64),)
[364.97556683]
(array([4], dtyp

[361.63234623]
(array([3], dtype=int64),)
[361.25272311]
(array([4], dtype=int64),)
[360.74282887]
(array([3], dtype=int64),)
[360.33629176]
(array([4], dtype=int64),)
[359.79122937]
(array([3], dtype=int64),)
[359.26806878]
(array([4], dtype=int64),)
[358.99452172]
(array([3], dtype=int64),)
[358.44482412]
(array([4], dtype=int64),)
[358.50849141]
(array([3], dtype=int64),)
[358.10394582]
(array([4], dtype=int64),)
[358.59152062]
(array([3], dtype=int64),)
[358.1301835]
(array([4], dtype=int64),)
[358.71323508]
(array([3], dtype=int64),)
[358.34357331]
(array([4], dtype=int64),)
[358.91309916]
(array([3], dtype=int64),)
[358.48635565]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array(

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], 

[365.27815004]
(array([3], dtype=int64),)
[365.03719451]
(array([4], dtype=int64),)
[363.84192193]
(array([3], dtype=int64),)
[363.79212416]
(array([4], dtype=int64),)
[362.79303048]
(array([3], dtype=int64),)
[362.43324875]
(array([4], dtype=int64),)
[362.02528693]
(array([3], dtype=int64),)
[361.96437406]
(array([4], dtype=int64),)
[361.49239081]
(array([3], dtype=int64),)
[361.23528245]
(array([4], dtype=int64),)
[360.97969907]
(array([3], dtype=int64),)
[360.67871384]
(array([4], dtype=int64),)
[360.56152424]
(array([3], dtype=int64),)
[360.24039658]
(array([4], dtype=int64),)
[360.32015575]
(array([3], dtype=int64),)
[359.85115482]
(array([4], dtype=int64),)
[360.00106901]
(array([3], dtype=int64),)
[359.70148314]
(array([4], dtype=int64),)
[359.77543916]
(array([3], dtype=int64),)
[359.48516844]
(array([4], dtype=int64),)
[359.4729261]
(array([3], dtype=int64),)
[359.24955065]
(array([4], dtype=int64),)
[359.3089166]
(array([3], dtype=int64),)
[359.0003852]
(array([4], dtype=int6

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[311.85107427]
(array([3], dtype=int64),)
[311.24354275]
(array([4], dtype=int64),)
[313.29430541]
(array([3], dtype=int64),)
[312.69049473]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=

[355.35605189]
(array([3], dtype=int64),)
[355.18957201]
(array([4], dtype=int64),)
[355.58633246]
(array([3], dtype=int64),)
[355.33878318]
(array([4], dtype=int64),)
[356.12971895]
(array([3], dtype=int64),)
[356.05074193]
(array([4], dtype=int64),)
[356.69553665]
(array([3], dtype=int64),)
[356.45718869]
(array([4], dtype=int64),)
[356.76768144]
(array([3], dtype=int64),)
[356.58778202]
(array([4], dtype=int64),)
[356.70320448]
(array([3], dtype=int64),)
[356.277259]
(array([4], dtype=int64),)
[356.08217145]
(array([3], dtype=int64),)
[355.85145042]
(array([4], dtype=int64),)
[355.54905469]
(array([3], dtype=int64),)
[355.22165971]
(array([4], dtype=int64),)
[355.04764908]
(array([3], dtype=int64),)
[354.7085593]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[298.05462796]
(array([9], dtype=int64),)
[298.03794525]
(array([10], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dty

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[355.96318585]
(array([3], dtype=int64),)
[355.83926605]
(array([4], dtype=int64),)
[356.42681624]
(array([3], dtype=int64),)
[356.32966089]
(array([4], dtype=int64),)
[357.47322874]
(array([3], dtype=int64),)
[357.41580996]
(array([4], dtype=int64),)
[358.30530107]
(array([3], dtype=int64),)
[358.28355362]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64)

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[302.35392]
(array([3], dtype=int64),)
[302.09641953]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=

[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[353.33718047]
(array([3], dtype=int64),)
[353.2100827]
(array([4], dtype=int64),)
[355.20410082]
(array([3], dtype=int64),)
[354.8057761]
(array([4], dtype=int64),)
[356.96672099]
(array([3], dtype=int64),)
[356.66440306]
(array([4], dtype=int64),)
[359.07954183]
(array([3], dtype=int64),)
[359.0204948]
(array([4], dtype=int64),)
[361.99998606]
(array([3], dtype=int64),)
[361.88806368]
(array([4], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[]
(array([], dtype=int64),)
[303.79517734]
(array([3], dtype=int64),)
[302.52479149]
(arr