In [4]:
import numpy as np
import pandas as pd
import xgboost
from xgboost import XGBRegressor

In [24]:
def shuju(a):
    data=pd.read_csv("D:/20年海洋/3000m以下/数据预处理/神经网络/"+str(a)+".csv")
    data1 = pd.DataFrame(data)
    monie=data1.iloc[:,4]
    train_label_e = data1.iloc[:,5]
    train_feature_e = data1.iloc[:, [1,2,3,4]]
    leng=len(monie)
    moniTem=data1.iloc[:,6]
    train_label_Tem = data1.iloc[:,7]
    train_feature_Tem = data1.iloc[:, [1,2,3,6]]

    monipressure=data1.iloc[:,8]
    train_label_pressure = data1.iloc[:,9]
    train_feature_pressure = data1.iloc[:, [1,2,3,8]]
    return monie,train_label_e,train_feature_e,moniTem,train_label_Tem,train_feature_Tem,monipressure,train_label_pressure,train_feature_pressure

In [25]:
def xunlian(moni,train_feature,train_label):
    from sklearn.model_selection import train_test_split
    x_train,x_test,y_train,y_test=train_test_split(train_feature,train_label,test_size=0.2,random_state=6)
    moni_test=[]
    for j in range(0,int(len(train_label)/5)):
        a=x_test.index.values[j]
        moni_test.append(moni[a])
    model = XGBRegressor(n_estimators=697,learning_rate=0.17)
    model.fit(x_train,y_train,eval_set=[(x_train, y_train),(x_test, y_test)],eval_metric='rmse' ,verbose='FALSE')
    pred = model.predict(x_test)
    score1 = model.score(x_train,y_train)
    score = model.score(x_test,y_test)
    print(score1)
    print(score)
    a = 0
    b=0
    print(pred.shape[0])
    for i in range(pred.shape[0]):
        print('pred:', pred[i], 'label:', y_test[x_test.index.values[i]],'moni:',moni_test[i])
        a+=np.abs(pred[i]-y_test[x_test.index.values[i]])
        b+=np.abs(y_test[x_test.index.values[i]]-moni_test[i])
    a=a/(len(train_label)/5)
    b=b/(len(train_label)/5)
    print(a,b)
    return model

In [ ]:
def xiuzheng(model):
    #时间
    data1=pd.read_csv("D:/20年海洋/数据/模拟数据/3000m层数层面导出数据/20170101nt1.csv" , encoding = "utf-8")
    data2 = pd.DataFrame(data1)
    x=data2.iloc[:,[4,5,8,10]]
    x=x.set_axis(['经度', '纬度', '高度', '模拟数据'], axis='columns', inplace=False)
    y = model.predict(x)

In [28]:
#时间
a='20170101_00'
monie,train_label_e,train_feature_e,moniTem,train_label_Tem,train_feature_Tem,monipressure,train_label_pressure,train_feature_pressure=shuju(a)
model1=xunlian(monie,train_feature_e,train_label_e)
model2=xunlian(moniTem,train_feature_Tem,train_label_Tem)
model3=xunlian(monipressure,train_feature_pressure,train_label_pressure)
#时间
data1=pd.read_csv("D:/20年海洋/数据/模拟数据/3000m层数层面导出数据/20170101nt1.csv" , encoding = "utf-8")
data2 = pd.DataFrame(data1)

x=data2.iloc[:,[4,5,8,9]]
x=x.set_axis(['lon', 'lat', 'z', 'monie'], axis='columns', inplace=False)
xiuzhenge = model1.predict(x)

x=data2.iloc[:,[4,5,8,10]]
x=x.set_axis(['lon', 'lat', 'z', 'monipressure'], axis='columns', inplace=False)
xiuzhengpressure = model3.predict(x)

x=data2.iloc[:,[4,5,8,11]]
x=x.set_axis(['lon', 'lat', 'z', 'moniTem'], axis='columns', inplace=False)
xiuzhengTem = model2.predict(x)
xiuzhenge,xiuzhengpressure,xiuzhengTem

0.9999998263002354
0.9912261660192678
162
pred: 22.786222 label: 22.73890296921161 moni: 23.19817259033142
pred: 11.408112 label: 11.793120397344612 moni: 11.632580128491039
pred: 8.544691 label: 8.791541979873077 moni: 8.837590209286859
pred: 8.306339 label: 8.456244264363058 moni: 8.706134267843339
pred: 9.753432 label: 8.523821224350574 moni: 10.59197350739386
pred: 24.04983 label: 24.46681603016861 moni: 22.62287830560668
pred: 15.374494 label: 15.510483636390324 moni: 16.132289605065893
pred: 9.294354 label: 9.075151935977098 moni: 7.749578543306392
pred: 28.971893 label: 29.111515959682013 moni: 28.55538414159782
pred: 23.209818 label: 22.194201527741562 moni: 24.78735442445651
pred: 10.448616 label: 10.637034256979273 moni: 8.73811404427337
pred: 13.832762 label: 13.75606195549788 moni: 13.202208073412411
pred: 19.464863 label: 19.462452572283162 moni: 19.63347079048119
pred: 29.365723 label: 29.401622107838122 moni: 28.88651418900982
pred: 25.831598 label: 26.966422946846752 mo

0.9999996845422423
0.9913198533209426
162
pred: 293.84915 label: 293.9314781604073 moni: 294.1758644572021
pred: 284.8218 label: 284.88552997448926 moni: 284.2591691428519
pred: 288.20364 label: 288.48542116388205 moni: 287.45510342352867
pred: 288.24326 label: 288.76495223409364 moni: 287.74143172686735
pred: 284.85144 label: 283.4395933618449 moni: 285.8729440505275
pred: 298.4275 label: 298.2506434230018 moni: 297.9922066431624
pred: 287.9987 label: 287.3075013854645 moni: 288.76138951937315
pred: 282.98166 label: 279.91850643437834 moni: 280.6368191782518
pred: 298.04742 label: 298.04829728577783 moni: 297.9464284280502
pred: 298.9629 label: 298.8482184713982 moni: 299.289390222565
pred: 287.3221 label: 287.1632857092518 moni: 288.23629511046767
pred: 286.5726 label: 286.881081232119 moni: 286.3502009289489
pred: 292.7567 label: 292.73180982199415 moni: 293.6871253933702
pred: 298.18573 label: 298.12638729307776 moni: 298.18205614745835
pred: 298.7531 label: 298.76011489428384 moni

0.999999998665507
0.9982102388817191
162
pred: 907.3132 label: 906.3904453705827 moni: 910.2308878392383
pred: 738.78644 label: 734.1607439075584 moni: 729.6143772728624
pred: 922.47363 label: 923.4201077576747 moni: 925.1637177967173
pred: 931.59564 label: 929.1557025385038 moni: 931.1716560891427
pred: 766.11847 label: 761.8506291776489 moni: 768.7217619717827
pred: 966.43945 label: 972.0743371486647 moni: 954.3731898075036
pred: 972.9994 label: 972.515611631624 moni: 978.8147926535717
pred: 718.649 label: 719.0814750548543 moni: 709.6613208571332
pred: 992.6611 label: 993.6226836578568 moni: 988.4262684165602
pred: 999.4609 label: 995.0663899164732 moni: 991.621926171248
pred: 977.39087 label: 978.3980911004712 moni: 969.669550029311
pred: 843.8768 label: 843.2856967771173 moni: 842.7197685265419
pred: 1001.9338 label: 1001.9993472057123 moni: 1011.864038416817
pred: 996.60425 label: 996.5100869066156 moni: 992.04548525008
pred: 994.8654 label: 995.624348811763 moni: 979.47629255658

(array([29.665482 , 29.601562 , 29.589941 , ...,  7.3628683,  7.2459097,
         7.210575 ], dtype=float32),
 array([1000.52014, 1000.3773 ,  999.8032 , ...,  745.72296,  736.9653 ,
         719.772  ], dtype=float32),
 array([297.8574 , 297.8999 , 297.97592, ..., 284.01572, 283.6453 ,
        282.1859 ], dtype=float32))

In [32]:
data3=data2.iloc[:,[0,1,2,3,4,5,6,7,8]]
xiuzhenge = pd.Series(xiuzhenge)
xiuzhenge.name = 'e'
xiuzhengTem = pd.Series(xiuzhengTem)
xiuzhengTem.name = 'Tem'
xiuzhengpressure = pd.Series(xiuzhengpressure)
xiuzhengpressure.name = 'pressure'
data4=pd.concat([data3,xiuzhenge,xiuzhengpressure,xiuzhengTem],axis=1)
#时间
data4.to_csv("D:/20年海洋/3000m以下/修正气象参数/20170101修正nt1.csv" , encoding = "utf-8", header=True, index=None)